import type { SituationVariant } from "@/domain/situations/situation-variant";

// Variantes de situacion de los 7 escenarios del curriculo
// "English for Software Engineers" (una fila por variante).
export const SITUATIONS_CURRICULUM: SituationVariant[] = [
  { id: "system_walkthrough.first_day_overview", scenarioType: "system_walkthrough", character: "onboarding", cefrLevels: ["A1", "A2", "B1"], stackHints: [], retired: false, title: "First-day overview of the system", framingDescription: "It's your new teammate's first day. Walk them through the main services, where the code lives, and how to run the app locally. Use plain, concrete language and confirm they can repeat the steps back to you." },
  { id: "system_walkthrough.quiet_environment_tour", scenarioType: "system_walkthrough", character: "routine", cefrLevels: ["A1", "A2", "B1"], stackHints: [], retired: false, title: "Routine environment tour", framingDescription: "Give a calm tour of the dev environment: repositories, the local database, and the one command that starts everything. Keep it simple and check understanding after each piece." },
  { id: "system_walkthrough.broken_setup", scenarioType: "system_walkthrough", character: "incident", cefrLevels: ["A2", "B1"], stackHints: ["devops"], retired: false, title: "Newcomer's setup is broken", framingDescription: "The new teammate's local environment won't start. Ask precise questions about what they see, where the files are, and which service is missing, then guide them to a working setup." },
  { id: "system_walkthrough.conflicting_docs", scenarioType: "system_walkthrough", character: "conflict", cefrLevels: ["A2", "B1"], stackHints: [], retired: false, title: "Outdated docs contradict the real system", framingDescription: "The onboarding docs describe a folder structure that no longer exists. Explain the mismatch clearly, point to what is actually true today, and note what should be fixed in the docs." },
  { id: "slack_thread.status_check", scenarioType: "slack_thread", character: "routine", cefrLevels: ["A1", "A2", "B1"], stackHints: [], retired: false, title: "Quick async status check", framingDescription: "Reply to a short Slack message asking for your current status. Keep every message brief, like real chat, and answer what's done, what's next, and any blocker." },
  { id: "slack_thread.new_hire_intro", scenarioType: "slack_thread", character: "onboarding", cefrLevels: ["A1", "A2", "B1", "B2"], stackHints: [], retired: false, title: "Welcoming a new hire in the team channel", framingDescription: "A new hire posted their first message in the team channel. Welcome them briefly, point them to one useful resource, and offer to help with anything specific." },
  { id: "slack_thread.urgent_blocker", scenarioType: "slack_thread", character: "incident", cefrLevels: ["A2", "B1", "B2"], stackHints: ["devops"], retired: false, title: "Urgent blocker flagged in the thread", framingDescription: "A teammate flags a production issue in the thread. Respond fast with short messages: ask the one question you need, offer immediate help, and confirm who owns the next step." },
  { id: "slack_thread.tone_misread", scenarioType: "slack_thread", character: "conflict", cefrLevels: ["A2", "B1", "B2"], stackHints: [], retired: false, title: "A short message came across as cold", framingDescription: "Your last one-line message landed as blunt and someone reacted badly. Clarify your tone in a couple of short messages without over-explaining, and keep the thread moving." },
  { id: "tech_comparison.database_choice", scenarioType: "tech_comparison", character: "routine", cefrLevels: ["A2", "B1"], stackHints: ["backend"], retired: false, title: "Choosing between two databases", framingDescription: "Compare two databases for a new service: one is faster to set up, the other scales better long-term. Use comparatives to explain trade-offs and recommend one with reasons." },
  { id: "tech_comparison.framework_disagreement", scenarioType: "tech_comparison", character: "conflict", cefrLevels: ["A2", "B1"], stackHints: ["frontend"], retired: false, title: "Team disagrees on a frontend framework", framingDescription: "Two teammates favor different frontend frameworks. Compare them fairly on learning curve, ecosystem, and performance, and help the team land on one choice." },
  { id: "tech_comparison.newcomer_asks_why", scenarioType: "tech_comparison", character: "onboarding", cefrLevels: ["A2", "B1"], stackHints: [], retired: false, title: "Explaining a past tech choice to a newcomer", framingDescription: "A new teammate asks why the team picked its current message queue over the alternative. Compare both simply and explain what made the difference at the time." },
  { id: "documentation_workshop.readme_draft", scenarioType: "documentation_workshop", character: "routine", cefrLevels: ["A2", "B1", "B2"], stackHints: [], retired: false, title: "Drafting a README together", framingDescription: "Draft a README for a new service live over chat. Cover what it does, how to run it, and how to test it, and let the reviewer push you toward a clearer structure." },
  { id: "documentation_workshop.pr_description_missing_why", scenarioType: "documentation_workshop", character: "conflict", cefrLevels: ["A2", "B1", "B2"], stackHints: [], retired: false, title: "PR description is missing the why", framingDescription: "Your PR description only says what changed, not why. Respond to the reviewer's pushback by adding the missing context and risks without getting defensive." },
  { id: "documentation_workshop.first_adr", scenarioType: "documentation_workshop", character: "onboarding", cefrLevels: ["A2", "B1", "B2"], stackHints: [], retired: false, title: "Writing your first ADR", framingDescription: "Write your first architecture decision record with guidance. Structure it as What / Why / How / Testing / Risks, and accept feedback on missing sections." },
  { id: "meeting_recap.decisions_only", scenarioType: "meeting_recap", character: "routine", cefrLevels: ["B1", "B2"], stackHints: [], retired: false, title: "Recap of a calm planning meeting", framingDescription: "Your manager missed a planning meeting. Recap the key decisions and who owns each action item, using reported speech instead of quoting everyone directly." },
  { id: "meeting_recap.conflicting_accounts", scenarioType: "meeting_recap", character: "conflict", cefrLevels: ["B1", "B2"], stackHints: [], retired: false, title: "Two people remember the meeting differently", framingDescription: "Your manager asks for a recap, but two attendees told you different things about what was agreed. Report both versions accurately and flag the discrepancy instead of picking one." },
  { id: "meeting_recap.incident_review_recap", scenarioType: "meeting_recap", character: "incident", cefrLevels: ["B1", "B2"], stackHints: ["devops"], retired: false, title: "Recapping an incident review", framingDescription: "Your manager missed the incident review. Recap what was said about root cause and next steps, using passive voice where the responsible party doesn't matter to the summary." },
  { id: "multi_team_sync.priority_clash", scenarioType: "multi_team_sync", character: "conflict", cefrLevels: ["B1", "B2", "C1"], stackHints: [], retired: false, title: "Two teams clash on priority", framingDescription: "Your team and another team both claim the same dependency is top priority. Interrupt politely when needed, ask for clarification, and push back on a timeline that doesn't work." },
  { id: "multi_team_sync.fast_paced_planning", scenarioType: "multi_team_sync", character: "routine", cefrLevels: ["B1", "B2", "C1"], stackHints: [], retired: false, title: "Fast-paced quarterly sync", framingDescription: "The sync covers many topics quickly with people talking over each other. Track the thread, ask for confirmation with question tags, and make sure your team's item gets airtime." },
  { id: "multi_team_sync.new_partner_team", scenarioType: "multi_team_sync", character: "onboarding", cefrLevels: ["B1", "B2", "C1"], stackHints: [], retired: false, title: "Syncing with a partner team for the first time", framingDescription: "This is the first sync with a newly formed partner team. Clarify how the two teams will communicate going forward and confirm shared expectations before the meeting ends." },
  { id: "multi_team_sync.dependency_at_risk", scenarioType: "multi_team_sync", character: "incident", cefrLevels: ["B1", "B2", "C1"], stackHints: ["devops"], retired: false, title: "A cross-team dependency is at risk", framingDescription: "A dependency owned by the other team is at risk of slipping and threatens your release. Push for a clear commitment, interrupting overlap and vague reassurances until you get one." },
  { id: "salary_negotiation.initial_offer", scenarioType: "salary_negotiation", character: "routine", cefrLevels: ["B2", "C1"], stackHints: [], retired: false, title: "Responding to the initial offer", framingDescription: "The recruiter presents an initial salary offer. Respond with a counter backed by market data, and negotiate one non-cash benefit as well." },
  { id: "salary_negotiation.competing_offer", scenarioType: "salary_negotiation", character: "conflict", cefrLevels: ["B2", "C1"], stackHints: [], retired: false, title: "Leveraging a competing offer", framingDescription: "You have a competing offer with a higher base salary. Bring it up professionally, without bluffing, and negotiate toward a number both sides can accept." },
  { id: "salary_negotiation.tight_deadline", scenarioType: "salary_negotiation", character: "incident", cefrLevels: ["B2", "C1"], stackHints: [], retired: false, title: "Negotiating under a tight deadline", framingDescription: "The recruiter needs your decision within 48 hours. Negotiate the terms you care about most under time pressure without agreeing to something you're not ready to accept." },
];
