/**
 * Unidades 13–18 (nivel B1) del libro «English for Software Engineers».
 *
 * El "why": transcripción fiel de la Parte 4 del libro fuente
 * (English-for-Software-Engineers-fuente.md) para alimentar los escenarios,
 * el coaching de chunks, el corrector de trampas y los retos de EMMA.
 * Datos puros: sin lógica, sin IO.
 */

import type { CurriculumUnit } from "@/domain/curriculum/unit";

export const UNITS_B1: CurriculumUnit[] = [
  {
    number: 13,
    title: "Code review without making enemies",
    cefrLevel: "B1",
    scenarioEs:
      "Revisas el PR de un compañero y encuentras tres problemas, uno de ellos grave. El code review es el único lugar donde tu inglés escrito queda registrado permanentemente y es leído por todo el equipo.",
    goalEs:
      "Criticar trabajo ajeno de forma que sea aceptada y no defendida: la crítica se formula como pregunta o como sugerencia, no como afirmación.",
    grammarFocus: [
      "Modales de especulación (might, could, may, must, can't)",
      "Especulación sobre el pasado: modal + have + participio (must have, could have, can't have, should have)",
      "Suavizadores (hedges): de apertura, de intensidad y de cierre",
      "Escalado de severidad (nit:, suggestion:, question:, blocking:)",
      "Preguntas indirectas sin inversión (I wonder if…, I was wondering why you did it)",
    ],
    soundFocus:
      "Entonación de la crítica suave: ascenso al final ↗ incluso en afirmaciones (apertura, invita a responder); descendente ↘ = sentencia cerrada. Con melodía plana española el mismo texto suena pasivo-agresivo. Además: have átono se reduce a /əv/ (must have → \"musta\", could have → \"coulda\").",
    chunks: [
      // A) Suavizadores de apertura (antes de la crítica)
      { text: "I might be missing something, but…", functionEs: "Suavizador de apertura: te haces responsable de un posible malentendido" },
      { text: "Correct me if I'm wrong, but…", functionEs: "Suavizador de apertura: te haces responsable de un posible malentendido" },
      { text: "I could be wrong here, but…", functionEs: "Suavizador de apertura antes de la crítica" },
      { text: "Maybe I'm misreading this, but…", functionEs: "Suavizador de apertura antes de la crítica" },
      { text: "Not sure if this is intentional, but…", functionEs: "Suavizador de apertura: permite que sea deliberado" },
      { text: "Just thinking out loud…", functionEs: "Suavizador de apertura: marca que no es una exigencia" },
      { text: "Out of curiosity, …", functionEs: "Suavizador de apertura: convierte la crítica en pregunta" },
      { text: "This may be out of scope, but…", functionEs: "Suavizador de apertura antes de la crítica" },
      // B) Suavizadores de intensidad (dentro de la frase)
      { text: "I'm a bit worried about the coupling here.", functionEs: "Suavizador de intensidad: a bit / slightly / somewhat reducen la fuerza" },
      { text: "It seems like the count isn't reset.", functionEs: "Suavizador de intensidad: seems / appears / looks like presentan la observación como apariencia" },
      { text: "These tend to get flaky over time.", functionEs: "Suavizador de intensidad: tend to expresa tendencia, no sentencia" },
      { text: "I think this could be simpler.", functionEs: "Suavizador de intensidad: I think / I feel / my sense is marcan opinión" },
      { text: "It's kind of doing two things at once.", functionEs: "Suavizador de intensidad: kind of / sort of aproximan" },
      { text: "That's arguably cleaner.", functionEs: "Suavizador de intensidad: arguably / perhaps / possibly matizan la afirmación" },
      // C) Suavizadores de cierre (después de la crítica)
      { text: "Happy to be wrong. / Happy to be talked out of it.", functionEs: "Suavizador de cierre: cede autoridad" },
      { text: "No strong feelings.", functionEs: "Suavizador de cierre: señala que no bloquearás por eso" },
      { text: "Non-blocking.", functionEs: "Suavizador de cierre: no bloqueante, término técnico estándar" },
      { text: "Your call. / Up to you.", functionEs: "Suavizador de cierre: delega la decisión" },
      { text: "Just a thought.", functionEs: "Suavizador de cierre tras la crítica" },
      { text: "Feel free to ignore.", functionEs: "Suavizador de cierre tras la crítica" },
      { text: "What do you think?", functionEs: "Suavizador de cierre: abre diálogo" },
      { text: "Does that make sense?", functionEs: "Suavizador de cierre: abre diálogo" },
      // D) Escalado de severidad
      { text: "nit: / minor: / nitpick:", functionEs: "Escalado de severidad: marca el comentario como opcional (convención muy extendida en equipos anglófonos)" },
      { text: "suggestion: / consider:", functionEs: "Escalado de severidad: marca el comentario como sugerencia" },
      { text: "question: / q:", functionEs: "Escalado de severidad: marca el comentario como pregunta" },
      { text: "I do feel more strongly about this one.", functionEs: "Escalado de severidad: indica que este punto sí importa" },
      { text: "blocking: / I'd like to see this changed before merging.", functionEs: "Escalado de severidad: marca el comentario como bloqueante" },
      // Preguntas indirectas
      { text: "I was wondering why you did it like this.", functionEs: "Pregunta indirecta: envuelve la pregunta en cláusula introductoria, sin inversión" },
      { text: "Do you know where the config is?", functionEs: "Pregunta indirecta con orden afirmativo (sin do/does/did)" },
      { text: "I'm not sure if it handles nulls.", functionEs: "Pregunta indirecta de sí/no con if/whether" },
      { text: "Any idea what the timeout is?", functionEs: "Pregunta indirecta informal" },
      // Recibir crítica
      { text: "Good catch.", functionEs: "Aceptar la crítica: respuesta estándar cuando alguien encuentra un bug real en tu código" },
      { text: "Fair point. / You're right. / Yeah, that's a bug. / Nice spot. / That's a much better approach.", functionEs: "Aceptar la crítica" },
      { text: "Fair point, though in this case… / I see what you mean, but… / That's true, although…", functionEs: "Aceptar parcialmente la crítica" },
      { text: "I did that on purpose because… / The reasoning was…", functionEs: "Explicar sin defenderse" },
      { text: "I went that way because X, but I'm not attached to it.", functionEs: "Explicar sin defenderse" },
      { text: "I'd push back on that one, actually. / I'm not sure I agree — here's my thinking. / Can I make the case for keeping it?", functionEs: "Discrepar con respeto" },
      { text: "Let me think about that one. / Can I come back to you on that?", functionEs: "Pedir tiempo antes de responder" },
      { text: "My mistake. / That's on me. / I missed that. / Good call, I hadn't considered that.", functionEs: "Reconocer un error propio" },
      { text: "Updated. / Done, thanks. / Addressed in the latest commit.", functionEs: "Cerrar el hilo de la crítica" },
    ],
    traps: [
      { wrong: "This is bad.", right: "I think this could be improved.", noteEs: "La crítica directa se lee como ataque" },
      { wrong: "You have to change this.", right: "Could we change this?", noteEs: "we en lugar de you despersonaliza" },
      { wrong: "Why did you…?", right: "What made you go with…? / Out of curiosity…", noteEs: "why + you suena acusatorio" },
      { wrong: "I don't agree. (a secas)", right: "I'd push back on that a bit." },
      { wrong: "It's obvious that…", right: "I'd have thought that…", noteEs: "obvious implica que el otro es tonto" },
      { wrong: "As I said before,…", right: "Just to build on that,…", noteEs: "as I said implica que no te escuchan" },
      { wrong: "You forgot X.", right: "It looks like X might be missing.", noteEs: "La pasiva evita culpar" },
      { wrong: "could of / should of", right: "could have / should have", noteEs: "Se escribe have; el error viene de que ambos suenan /əv/" },
      { wrong: "I was wondering why did you…", right: "…why you did…", noteEs: "Sin inversión en preguntas indirectas" },
      { wrong: "It mustn't be the network.", right: "It can't be the network.", noteEs: "mustn't nunca significa \"deduzco que no\": para eso se usa can't" },
      { wrong: "Sorry for my English.", right: "(no lo digas)", noteEs: "Resta autoridad sin ganar nada" },
    ],
    challenges: [
      {
        id: 27,
        instructionsEs:
          "Coge un pull request real (tuyo o de un compañero) y escribe tres comentarios en inglés: uno nit, uno de sugerencia con pregunta indirecta, y uno bloqueante bien justificado. El bloqueante debe explicar la consecuencia del problema, no solo señalarlo.",
        criteria: [
          "Un comentario nit",
          "Un comentario de sugerencia que usa pregunta indirecta",
          "Un comentario bloqueante bien justificado que explica la consecuencia del problema, no solo lo señala",
        ],
        mode: "written",
      },
      {
        id: 28,
        instructionsEs:
          "Escribe la respuesta del autor a esos tres comentarios: aceptando uno, aceptando parcialmente otro y discrepando con respeto del tercero.",
        criteria: [
          "Una respuesta que acepta un comentario",
          "Una respuesta que acepta parcialmente otro",
          "Una respuesta que discrepa con respeto del tercero",
        ],
        mode: "written",
      },
      {
        id: 29,
        instructionsEs:
          "Autoauditoría: revisa los últimos diez comentarios de code review que hayas escrito en inglés. Cuenta cuántos empiezan con un suavizador. Si son menos de la mitad, tienes una tarea concreta para el próximo mes.",
        criteria: [
          "Diez comentarios reales revisados",
          "Conteo de cuántos empiezan con un suavizador",
          "Si son menos de la mitad, definir la tarea concreta para el próximo mes",
        ],
        mode: "real-work",
      },
    ],
    scenarioTypes: ["code_review"],
  },
  {
    number: 14,
    title: "Cause, effect and the order of events",
    cefrLevel: "B1",
    scenarioEs:
      "Explicas una cadena causal compleja: qué había pasado antes de que fallara, qué lo provocó y qué consecuencias tuvo (postmortem de un incidente).",
    goalEs: "Ordenar eventos en el tiempo con precisión y expresar causalidad.",
    grammarFocus: [
      "Pasado perfecto (had + participio): el evento más antiguo va en had + participio, el más reciente en pasado simple",
      "Pasado perfecto continuo (had been + -ing): duración de una actividad antes de un momento pasado",
      "Conectores de causa (because + oración, because of / due to + sustantivo, the reason…is that, stem from)",
      "Conectores de consecuencia (so, therefore, as a result, which meant, led to / resulted in, ended up + -ing)",
      "Contraste y concesión (however, although + oración, despite + sustantivo/-ing, whereas)",
    ],
    soundFocus:
      "had y 'd son casi inaudibles: had átono /həd/, had been /(h)əd bɪn/ → \"'d-bin\", hadn't fuerte /ˈhædənt/. Es la razón por la que muchos hispanohablantes no producen nunca el pasado perfecto: no lo oyen. Frase de entrenamiento: \"By the time we noticed, it'd been failing for hours and nobody'd looked at the logs.\"",
    chunks: [
      // Marcadores de pasado perfecto
      { text: "By the time X, Y had already…", functionEs: "Contraste temporal: marcar qué había pasado antes de otro evento pasado" },
      { text: "It turned out that someone had…", functionEs: "Revelar un hecho anterior descubierto después" },
      { text: "I realised I had forgotten to…", functionEs: "Darse cuenta de una omisión anterior" },
      { text: "Until then, nobody had noticed.", functionEs: "Marcar que algo pasó inadvertido hasta un momento pasado" },
      { text: "This was the first time it had happened.", functionEs: "Marcar la novedad de un evento en un relato en pasado" },
      { text: "I had never seen that error before.", functionEs: "Experiencia previa negada en un relato en pasado" },
      // Chunks de postmortem
      { text: "At 02:14 UTC, X began…", functionEs: "Timeline del postmortem" },
      { text: "The root cause was…", functionEs: "Declarar la causa raíz" },
      { text: "The trigger was…", functionEs: "Declarar el detonante (detonante ≠ causa raíz)" },
      { text: "Contributing factors were…", functionEs: "Enumerar factores contribuyentes" },
      { text: "The reason X didn't happen is that…", functionEs: "Explicar por qué algo no ocurrió" },
      { text: "Impact: X minutes of downtime, roughly Y failed requests.", functionEs: "Cuantificar el impacto del incidente" },
      { text: "The issue had been present since…", functionEs: "Marcar desde cuándo existía el problema" },
      { text: "It hadn't caused problems because…", functionEs: "Explicar por qué no había causado problemas antes" },
      { text: "This was the first time we'd seen…", functionEs: "Marcar la novedad del fallo" },
      { text: "In hindsight, we should have…", functionEs: "Retrospectiva: crítica de algo no hecho" },
      { text: "What went well… / What didn't…", functionEs: "Secciones estándar del postmortem" },
      { text: "Action items", functionEs: "Sección estándar de acciones del postmortem" },
      { text: "To prevent recurrence, we're going to…", functionEs: "Plan para evitar la repetición" },
      { text: "No customer data was lost.", functionEs: "Tranquilizar sobre el alcance del incidente" },
      { text: "We got lucky — it could have been much worse.", functionEs: "Reconocer que el impacto pudo ser mayor" },
      { text: "blameless postmortem", functionEs: "Postmortem sin culpables" },
    ],
    traps: [
      { wrong: "because of it was slow", right: "because it was slow", noteEs: "because va con oración; because of va con sustantivo" },
      { wrong: "due to the pool was full", right: "because the pool was full", noteEs: "due to va con sustantivo, no con oración" },
      { wrong: "Despite it was low", right: "Although it was low / Despite the low volume", noteEs: "although + oración · despite + sustantivo o -ing" },
      { wrong: "It failed, however we recovered.", right: "It failed. However, we recovered.", noteEs: "however no es una conjunción como but: usa punto o punto y coma antes" },
      { wrong: "The reason is because…", right: "The reason is that…" },
      { wrong: "When I had arrived…", right: "When I arrived…", noteEs: "El evento posterior va en pasado simple" },
      { wrong: "had been introduced three weeks ago", right: "…three weeks earlier / before", noteEs: "ago se ancla al presente; en relato pasado usa earlier/before" },
      { wrong: "It resulted in fail.", right: "It resulted in failure / in failing." },
      { wrong: "This caused that the service crashed.", right: "This caused the service to crash." },
      { wrong: "In the end we ended up to roll back.", right: "We ended up rolling back.", noteEs: "ended up + -ing" },
    ],
    challenges: [
      {
        id: 30,
        instructionsEs:
          "Escribe un postmortem completo de un incidente real (o inventado plausible) con estas secciones: Summary, Timeline (mínimo cuatro entradas con hora), Root cause, Contributing factors, Impact, What went well, Action items.",
        criteria: [
          "Secciones completas: Summary, Timeline, Root cause, Contributing factors, Impact, What went well, Action items",
          "Timeline con mínimo cuatro entradas con hora",
          "Cuatro pasados perfectos",
          "Un pasado perfecto continuo",
          "Cuatro conectores causales distintos",
          "Voz pasiva donde sea apropiado para no señalar personas",
        ],
        mode: "written",
      },
      {
        id: 31,
        instructionsEs:
          "Presenta ese postmortem en voz alta (3 minutos). La estructura oral estándar es: \"I'll walk you through what happened, then the root cause, then what we're changing.\" Grábate y comprueba si produces los had o si te comes el pasado perfecto.",
        criteria: [
          "Duración de unos 3 minutos",
          "Estructura oral estándar: qué pasó, causa raíz, qué cambiamos",
          "Grabación revisada comprobando la producción de los had (pasado perfecto)",
        ],
        mode: "oral",
      },
    ],
    scenarioTypes: ["incident_postmortem"],
  },
  {
    number: 15,
    title: "Hypotheticals: conditionals for architecture and trade-offs",
    cefrLevel: "B1",
    scenarioEs:
      "Una discusión de diseño donde hay que razonar sobre escenarios que no han pasado (fragmentar una tabla, archivar datos, evaluar el crecimiento).",
    goalEs: "Razonar sobre consecuencias hipotéticas, plantear alternativas y evaluar riesgos.",
    grammarFocus: [
      "Condicional cero (verdad general), primero (posibilidad real) y segundo (hipotético: pasado simple = distancia de la realidad)",
      "will y would nunca van dentro de la cláusula if",
      "were para todas las personas en el segundo condicional formal (If I were you)",
      "Modales en la cláusula principal para ajustar la certeza (might, should, could, 'll have to)",
      "Alternativas a if: unless, as long as / provided that, in case, whether…or not, suppose, what if, assuming, otherwise, even if, only if",
    ],
    soundFocus:
      "would y su contracción 'd, casi invisible al oído: would átono /wəd/, would have /ˈwʊdəv/ → \"wooda\". Par mínimo peligroso: I'd /aɪd/ vs I /aɪ/ — la /d/ es la única diferencia entre sonar B1 y sonar A2.",
    chunks: [
      { text: "What if we didn't…?", functionEs: "Plantear la alternativa nula" },
      { text: "What happens if…?", functionEs: "Preguntar por la consecuencia" },
      { text: "Suppose growth doubled — then what?", functionEs: "Plantear un escenario hipotético" },
      { text: "Assuming growth stays flat, …", functionEs: "Hacer explícita la premisa" },
      { text: "That would buy us eighteen months.", functionEs: "Ganar tiempo con una solución provisional" },
      { text: "I'd rather X than Y.", functionEs: "Expresar preferencia" },
      { text: "I'd lean towards…", functionEs: "Expresar inclinación" },
      { text: "As long as we're honest that it's a deferral…", functionEs: "Condición de aceptación" },
      { text: "Let's write down the trigger.", functionEs: "Definir cuándo revisar la decisión" },
      { text: "Let's revisit this if X.", functionEs: "Acordar la condición de reconsideración" },
      { text: "That's a reasonable stopgap.", functionEs: "Valorar una solución provisional" },
      { text: "We'd be back here in nine months.", functionEs: "Proyectar la consecuencia hipotética" },
      { text: "It depends on how you look at it.", functionEs: "Relativizar la valoración" },
      { text: "Devil's advocate for a second: …", functionEs: "Hacer de abogado del diablo" },
      { text: "Playing that out, …", functionEs: "Seguir ese razonamiento hasta su consecuencia" },
      { text: "The failure mode I'm worried about is…", functionEs: "Expresar un riesgo con precisión" },
    ],
    traps: [
      { wrong: "If we would do X…", right: "If we did X…", noteEs: "would nunca va dentro de la cláusula if" },
      { wrong: "If it will fail…", right: "If it fails…", noteEs: "will nunca va dentro de la cláusula if" },
      { wrong: "Unless we don't do it", right: "Unless we do it", noteEs: "unless ya es negativo" },
      { wrong: "In case of it fails", right: "In case it fails", noteEs: "in case + oración / in case of + sustantivo" },
      { wrong: "If I would be you", right: "If I were you" },
      { wrong: "I would like that you review it.", right: "I'd like you to review it." },
      { wrong: "It would be better that we wait.", right: "It would be better to wait / if we waited." },
      { wrong: "even if / even though confundidos", right: "even if = incluso si (hipotético) · even though = aunque (real)" },
      { wrong: "otherwise usado como on the other hand", right: "otherwise = si no · on the other hand = por otro lado" },
      { wrong: "In case that", right: "In case (sin that)" },
    ],
    challenges: [
      {
        id: 32,
        instructionsEs:
          "Escribe una discusión de diseño de 12–15 frases sobre una decisión real de tu sistema.",
        criteria: [
          "12–15 frases",
          "Dos condicionales cero",
          "Dos condicionales primeros",
          "Tres condicionales segundos",
          "Un unless",
          "Un as long as",
          "Un in case",
          "Un cierre que define el trigger de revisión",
        ],
        mode: "written",
      },
      {
        id: 33,
        instructionsEs:
          "Oral (3 min): defiende una decisión de arquitectura que consideres correcta y que otros discutan. Estructura: \"The way I see it, if we X, then Y. The alternative would be Z, but that would mean W. I'd lean towards X as long as we…\".",
        criteria: [
          "Duración de unos 3 minutos",
          "Sigue la estructura: The way I see it, if we X, then Y / The alternative would be Z, but that would mean W / I'd lean towards X as long as we…",
        ],
        mode: "oral",
      },
      {
        id: 34,
        instructionsEs:
          "Escribe un ADR (Architecture Decision Record) corto en inglés con las secciones estándar: Context, Options considered (mínimo dos, cada una con \"If we did this…\"), Decision, Consequences, When to revisit.",
        criteria: [
          "Secciones estándar: Context, Options considered, Decision, Consequences, When to revisit",
          "Mínimo dos opciones consideradas",
          "Cada opción incluye un \"If we did this…\"",
        ],
        mode: "written",
      },
    ],
    scenarioTypes: ["design_review", "architecture_pitch"],
  },
  {
    number: 16,
    title: "Passive voice and reporting what people said",
    cefrLevel: "B1",
    scenarioEs:
      "Escribes las actas de una reunión, un postmortem sin culpables, o resumes a tu equipo lo que dijo otro equipo.",
    goalEs: "Describir procesos sin agente y reportar el discurso ajeno con precisión.",
    grammarFocus: [
      "Voz pasiva completa en todos los tiempos (be + participio; agente con by): activa por defecto, pasiva cuando tenga una razón",
      "Pasiva con dos objetos: el inglés prefiere la persona como sujeto (I was given access)",
      "Estructuras impersonales (It was decided that…, X is expected to…, X is to be + participio)",
      "Reported speech: los tiempos retroceden un paso (y cambian pronombres y deícticos: now → then, tomorrow → the next day)",
      "Preguntas reportadas sin inversión y sin do/does/did",
      "Verbos introductores con su patrón (suggest + that/-ing, deny + -ing vs refuse + to, warn/remind/tell + objeto)",
    ],
    soundFocus:
      "En la pasiva, be y been son átonos y el acento cae en el participio (It has been dePLOYED). been siempre /bɪn/ átono; has been → /(h)əz bɪn/ → \"'zbin\". Un hispanohablante acentúa el auxiliar y suena raro.",
    chunks: [
      { text: "It was decided that…", functionEs: "Registro impersonal de decisiones" },
      { text: "It has been agreed that…", functionEs: "Registrar un acuerdo sin señalar agente" },
      { text: "It is said / thought / believed that…", functionEs: "Afirmación impersonal (It's believed to be a driver issue)" },
      { text: "X is known to…", functionEs: "Comportamiento conocido (This library is known to leak memory)" },
      { text: "X is expected to…", functionEs: "Expectativa (Latency is expected to drop by 30%)" },
      { text: "X is supposed to…", functionEs: "Comportamiento previsto (It's supposed to retry three times)" },
      { text: "X is to be + participio", functionEs: "Plan formal (The call sites are to be documented)" },
      { text: "There is said to be…", functionEs: "Rumor o creencia impersonal" },
      { text: "I was given access on Monday.", functionEs: "Pasiva con persona como sujeto (en español: \"me dieron acceso\")" },
      { text: "The ticket has been assigned to X.", functionEs: "Actas: registrar asignación sin agente" },
      { text: "A follow-up has been scheduled for…", functionEs: "Actas: registrar seguimiento programado" },
      { text: "A migration guide will be published by…", functionEs: "Action item en pasiva con plazo" },
      { text: "He pointed out that…", functionEs: "Verbo introductor: señalar un hecho relevante" },
      { text: "She suggested that we… / suggested + -ing", functionEs: "Verbo introductor: proponer (nunca *suggested me to*)" },
      { text: "They warned us that… / warned us not to…", functionEs: "Verbo introductor: advertir" },
      { text: "He admitted that…", functionEs: "Verbo introductor: reconocer algo negativo" },
      { text: "They offered to…", functionEs: "Verbo introductor: ofrecerse a hacer algo" },
      { text: "He denied + -ing", functionEs: "Negar que algo ocurrió (≠ refuse to + inf = negarse a hacerlo)" },
      { text: "She flagged that…", functionEs: "Verbo introductor corporativo: señalar un riesgo" },
      { text: "He pushed back on…", functionEs: "Verbo introductor corporativo: objetar" },
      { text: "They asked whether we were ready.", functionEs: "Pregunta reportada: sin inversión, con whether/if" },
      { text: "They told us to migrate by June. / They told us not to deploy on Friday.", functionEs: "Orden reportada con tell + objeto + (not) to + infinitivo" },
    ],
    traps: [
      { wrong: "He said me…", right: "He told me… / He said…", noteEs: "tell necesita objeto de persona; say no lo lleva" },
      { wrong: "He suggested me to…", right: "He suggested that I… / suggested + -ing" },
      { wrong: "He explained me…", right: "He explained X to me" },
      { wrong: "It was decide…", right: "It was decided", noteEs: "La pasiva lleva participio" },
      { wrong: "Is expected that…", right: "It is expected that…", noteEs: "El inglés exige el sujeto it" },
      { wrong: "He asked me if I had finished?", right: "He asked me if I had finished.", noteEs: "Sin signo de interrogación: es afirmación" },
      { wrong: "The bug was fixed for Maya.", right: "The bug was fixed by Maya.", noteEs: "El agente de la pasiva va con by" },
      { wrong: "I was said that…", right: "I was told that…" },
      { wrong: "It's supposed to work, no?", right: "It's supposed to work, isn't it?" },
      { wrong: "He informed me that he will come.", right: "He informed me that he would come.", noteEs: "Retroceso de tiempos en el discurso referido" },
    ],
    challenges: [
      {
        id: 35,
        instructionsEs:
          "Escribe las actas de una reunión real a la que hayas asistido, en inglés, 12–15 frases.",
        criteria: [
          "12–15 frases",
          "Seis verbos introductores distintos (no repitas said)",
          "Cuatro pasivas",
          "Dos preguntas reportadas",
          "Una sección de Action items con will be / is to be",
        ],
        mode: "written",
      },
      {
        id: 36,
        instructionsEs:
          "Reescribe un párrafo de postmortem que señale a una persona, convirtiéndolo en blameless mediante pasivas y estructuras impersonales. Compara los dos textos: mismo contenido factual, efecto muy distinto.",
        criteria: [
          "Versión blameless con pasivas y estructuras impersonales",
          "Mismo contenido factual en ambos textos",
          "Comparación explícita del efecto de las dos versiones",
        ],
        mode: "written",
      },
    ],
    scenarioTypes: ["meeting_recap", "retrospective"],
  },
  {
    number: 17,
    title: "Surviving a meeting in real time",
    cefrLevel: "B1",
    scenarioEs:
      "Una reunión de veinte personas donde no controlas el ritmo, se solapan las voces y necesitas intervenir. Aquí la solución no es más gramática: es tener frases prefabricadas de acceso instantáneo.",
    goalEs:
      "Entrar, ganar tiempo, pedir aclaración, discrepar, redirigir y cerrar. Automatizar cuarenta frases hasta que salgan sin pensar.",
    grammarFocus: [
      "Lenguaje funcional (repertorio de chunks de acceso instantáneo)",
      "Question tags: afirmativo → tag negativo y viceversa; se repite el auxiliar (alternativa universal: right?)",
      "Repetición estratégica y paráfrasis para confirmar comprensión",
      "Fillers ingleses (well, I mean, actually, basically) en lugar de silencios",
    ],
    soundFocus:
      "Entonación de los question tags: descendente ↘ = espero acuerdo, no es pregunta real; ascendente ↗ = pregunta genuina. Fillers ingleses (um, well, so, I mean, you know, actually, basically, sort of, let's see) en lugar de silencios o \"eh…\": la percepción de fluidez depende más del ritmo que de la corrección.",
    chunks: [
      // A) Ganar tiempo
      { text: "That's a good question.", functionEs: "Ganar tiempo (nunca te quedes en silencio), registro neutro" },
      { text: "Let me think about that for a second.", functionEs: "Ganar tiempo" },
      { text: "Hmm, good point — let me unpack that.", functionEs: "Ganar tiempo" },
      { text: "So, the way I see it is…", functionEs: "Ganar tiempo mientras arrancas la respuesta" },
      { text: "Right, so…", functionEs: "Ganar tiempo: muletilla legítima" },
      { text: "Well, it depends.", functionEs: "Ganar tiempo" },
      { text: "Off the top of my head, …", functionEs: "Ganar tiempo: responder sin comprometerse con el dato exacto" },
      { text: "I'd have to check, but I think…", functionEs: "Ganar tiempo sin inventar" },
      { text: "Can I come back to you on that?", functionEs: "Aplazar honestamente una respuesta" },
      { text: "Let me rephrase that.", functionEs: "Reformular si te has trabado" },
      // B) Pedir aclaración
      { text: "Sorry, could you say that again?", functionEs: "Pedir aclaración: no oíste (nunca digas \"What?\")" },
      { text: "Sorry, I didn't catch that.", functionEs: "Pedir aclaración: no oíste" },
      { text: "Could you repeat the last part?", functionEs: "Pedir aclaración: oíste parcialmente" },
      { text: "Sorry, you're breaking up.", functionEs: "Pedir aclaración: mala conexión" },
      { text: "Could you speak up a bit?", functionEs: "Pedir aclaración: volumen bajo" },
      { text: "Sorry, could you slow down a little? I want to make sure I follow.", functionEs: "Pedir aclaración: demasiado rápido (aceptable en cualquier reunión profesional)" },
      { text: "Just to make sure I understand — you mean X, right?", functionEs: "Confirmar contenido" },
      { text: "When you say \"X\", do you mean…?", functionEs: "Aclarar un término" },
      { text: "Sorry, I'm not following. Could you walk me through that again?", functionEs: "Pedir aclaración: perdido del todo" },
      { text: "Can you give me an example?", functionEs: "Pedir concreción" },
      { text: "So if I understand correctly, …", functionEs: "Parafrasear para confirmar" },
      { text: "Let me play that back to you: …", functionEs: "Confirmar comprensión repitiendo el plan" },
      // C) Interrumpir (con permiso)
      { text: "Sorry, can I jump in here?", functionEs: "Interrumpir: fórmula estándar" },
      { text: "Can I add something to that?", functionEs: "Interrumpir para complementar" },
      { text: "Sorry to interrupt, but…", functionEs: "Interrumpir con disculpa" },
      { text: "Just quickly on that point…", functionEs: "Interrumpir brevemente" },
      { text: "If I could just add one thing…", functionEs: "Interrumpir, registro formal" },
      { text: "Before we move on, can I ask about X?", functionEs: "Frenar el avance de la reunión" },
      { text: "Sorry, I think we might be talking about two different things.", functionEs: "Detectar un malentendido" },
      // D) Discrepar (la escala completa)
      { text: "I see your point, but I'm not sure it applies here.", functionEs: "Discrepar, fuerza muy suave" },
      { text: "That's fair, although I'd add that…", functionEs: "Discrepar, fuerza muy suave" },
      { text: "I'd look at it slightly differently.", functionEs: "Discrepar, fuerza muy suave" },
      { text: "Hmm, I'm not convinced. My concern is that…", functionEs: "Discrepar, fuerza media" },
      { text: "I'd push back on that a bit.", functionEs: "Discrepar, fuerza media" },
      { text: "I take a different view on that.", functionEs: "Discrepar, fuerza media" },
      { text: "I disagree, and here's why: …", functionEs: "Discrepar, fuerza firme" },
      { text: "I'd argue the opposite, actually.", functionEs: "Discrepar, fuerza firme" },
      { text: "I have to disagree with that.", functionEs: "Discrepar, muy firme (usar con cuidado)" },
      { text: "I think that's a mistake, and I want to be on record.", functionEs: "Discrepar, muy firme (usar con cuidado)" },
      // E) Estar de acuerdo
      { text: "Exactly. / Absolutely.", functionEs: "Acuerdo fuerte" },
      { text: "That's a fair point.", functionEs: "Conceder un punto" },
      { text: "I'm with you on that.", functionEs: "Expresar acuerdo" },
      { text: "That's my read too.", functionEs: "Coincidir en la interpretación" },
      { text: "Good point — I hadn't thought of that.", functionEs: "Reconocer un buen argumento" },
      { text: "Agreed.", functionEs: "Acuerdo breve, escrito y oral" },
      { text: "I'd second that.", functionEs: "Apoyar una propuesta" },
      { text: "That makes sense.", functionEs: "Expresar acuerdo" },
      { text: "I'm fine either way.", functionEs: "Indiferencia entre opciones" },
      // F) Proponer y decidir
      { text: "Can I make a suggestion?", functionEs: "Introducir una propuesta" },
      { text: "How about we…?", functionEs: "Proponer" },
      { text: "What if we…?", functionEs: "Proponer una alternativa" },
      { text: "Shall we park that for now?", functionEs: "Aparcar un tema" },
      { text: "Let's take this offline.", functionEs: "Sacar la discusión de la reunión" },
      { text: "Can we timebox this to five minutes?", functionEs: "Limitar el tiempo de la discusión" },
      { text: "Are we all aligned on that?", functionEs: "Verificar consenso" },
      { text: "So, to summarise: …", functionEs: "Resumir" },
      { text: "Where does that leave us?", functionEs: "Pedir conclusión" },
      { text: "What's the next step?", functionEs: "Pedir el siguiente paso" },
      { text: "Who's taking that?", functionEs: "Asignar responsable" },
      { text: "Can I get an action item on that?", functionEs: "Pedir que quede registrado como acción" },
      { text: "Let's put a pin in that.", functionEs: "Dejarlo apuntado para más tarde" },
      // G) Cerrar y salir
      { text: "I think we're out of time.", functionEs: "Cerrar la reunión" },
      { text: "Let's wrap up.", functionEs: "Cerrar la reunión" },
      { text: "I'll follow up in writing.", functionEs: "Cerrar: confirmar por escrito después" },
      { text: "I'll send round the notes.", functionEs: "Cerrar: comprometerse a enviar las notas" },
      { text: "Anything else before we close?", functionEs: "Cerrar: última ronda" },
      { text: "Thanks everyone.", functionEs: "Cerrar y despedirse" },
      { text: "I have a hard stop at 3.", functionEs: "Avisar previamente de que te vas puntual" },
    ],
    traps: [
      { wrong: "What?", right: "Sorry, could you repeat that?" },
      { wrong: "Repeat please.", right: "Could you say that again?" },
      { wrong: "I don't understand nothing.", right: "I don't understand anything. / I'm not following." },
      { wrong: "Explain me again.", right: "Could you explain that again?" },
      { wrong: "Speak slowly.", right: "Could you slow down a bit?" },
      { wrong: "You're wrong.", right: "I'd look at it differently.", noteEs: "Técnicamente correcta y socialmente costosa" },
      { wrong: "I want to say something.", right: "Can I jump in?" },
      { wrong: "Sorry for my English.", right: "(omítelo)" },
      { wrong: "Excuse me (para interrumpir a mitad de frase)", right: "Sorry, can I jump in?" },
      { wrong: "Is it clear? (tras explicar)", right: "Does that make sense?" },
      { wrong: "For finish…", right: "To wrap up…" },
      { wrong: "In conclusion (en habla informal)", right: "So, basically… / So, to summarise…" },
    ],
    challenges: [
      {
        id: 37,
        instructionsEs:
          "Memorización: elige veinte chunks de esta unidad —los que más necesitarías esta semana— y créalos como tarjetas de repaso espaciado con formato de producción: anverso en español o descripción de situación, reverso en inglés. Repásalos a diario. Es la única unidad del libro con memorización pura, porque en una reunión no hay tiempo de construir.",
        criteria: [
          "Veinte chunks elegidos según tu necesidad de la semana",
          "Tarjetas en formato de producción: anverso en español o situación, reverso en inglés",
          "Repaso espaciado diario",
        ],
        mode: "memorization",
      },
      {
        id: 38,
        instructionsEs:
          "Simulación: graba una reunión simulada de dos minutos donde tú hagas los cinco actos: interrumpir, pedir aclaración, discrepar, proponer y resumir. Puedes hacerlo solo, interpretando ambas partes.",
        criteria: [
          "Grabación de unos dos minutos",
          "Los cinco actos presentes: interrumpir, pedir aclaración, discrepar, proponer y resumir",
        ],
        mode: "oral",
      },
      {
        id: 39,
        instructionsEs:
          "Real: en tu próxima reunión en inglés, comprométete a hacer una intervención usando uno de estos chunks. Solo una. Anota cuál usaste y cómo fue. Repite cada semana subiendo a dos, tres, cuatro.",
        criteria: [
          "Una intervención real con un chunk de la unidad",
          "Registro de cuál usaste y cómo fue",
          "Repetición semanal con incremento progresivo (dos, tres, cuatro)",
        ],
        mode: "real-work",
      },
    ],
    scenarioTypes: ["multi_team_sync", "release_planning", "retrospective"],
  },
  {
    number: 18,
    title: "Describing systems with precision",
    cefrLevel: "B1",
    scenarioEs:
      "Explicas un sistema en una pizarra, en un documento de diseño o en una entrevista.",
    goalEs: "Definir, especificar y añadir información sin ambigüedad.",
    grammarFocus: [
      "Oraciones de relativo definidas (sin comas; that el más frecuente en inglés técnico; omisión del relativo objeto)",
      "Oraciones de relativo no definidas (entre comas; nunca that; la coma cambia el significado)",
      "whose (posesión), where (lugar), which referido a toda la frase anterior",
      "Relativos con preposición (informal al final: the service I'm talking about) y con cuantificador (most of which, all of which)",
      "Cláusulas de participio: activa → -ing, pasiva → participio de pasado; cuidado con el dangling participle",
      "Aposición: dos sustantivos entre comas, el segundo define el primero",
    ],
    soundFocus:
      "Las relativas se marcan con pausas que corresponden a las comas: definidas sin pausa (un solo grupo tonal); no definidas con pausas reales. Leer todo sin pausas hace ambiguas las explicaciones. Relativos: that átono /ðət/ (no /ðæt/), whose /huːz/, whom /huːm/.",
    chunks: [
      { text: "The service that handles payments is…", functionEs: "Relativa definida para identificar un componente" },
      { text: "…, which runs in Kubernetes, …", functionEs: "Relativa no definida: añadir un dato no esencial entre comas" },
      { text: "Postgres, where the transactional data lives", functionEs: "where para ubicar dónde viven los datos" },
      { text: "Requests whose signature doesn't match are rejected.", functionEs: "whose para posesión sobre cosas o personas" },
      { text: "The pool was exhausted, which meant new requests timed out.", functionEs: "which referido a toda la frase anterior" },
      { text: "There's a worker, called `settlement-runner`, that…", functionEs: "Presentar un componente: participio + relativa definida" },
      { text: "The file, generated at 23:00 every night, is uploaded to…", functionEs: "Cláusula de participio reducida (pasiva → participio de pasado)" },
      { text: "The part I'd change if I could is…", functionEs: "Relativo objeto omitido (más natural)" },
      { text: "two databases, one of which is Postgres", functionEs: "Cuantificador + of which para enumerar componentes" },
      { text: "five services, most of which are stateless", functionEs: "Cuantificador + of which" },
      { text: "three call sites, all of which need updating", functionEs: "Cuantificador + of which" },
      { text: "Built on top of Kafka, the service can replay events.", functionEs: "Cláusula de participio al inicio de frase (escritura técnica)" },
      { text: "Having deployed the fix, we monitored for an hour.", functionEs: "Cláusula de participio perfecta al inicio" },
      { text: "Once deployed, the change takes effect immediately.", functionEs: "Participio con once para secuenciar" },
      { text: "When called with no arguments, it returns the default.", functionEs: "Participio con when para condiciones de invocación" },
      { text: "Redis, our cache layer, holds the idempotency keys.", functionEs: "Aposición: la forma más rápida de definir" },
      { text: "At a high level, there are three components. The first one, which handles X, …", functionEs: "Apertura de explicación de arquitectura en pizarra o entrevista" },
    ],
    traps: [
      { wrong: "the service who handles", right: "the service that/which handles", noteEs: "who solo para personas" },
      { wrong: "Redis, that we use…", right: "Redis, which we use…", noteEs: "Las no definidas nunca usan that" },
      { wrong: "the repo where I told you about", right: "the repo that I told you about / about which" },
      { wrong: "We have five services, most of them are stateless.", right: "We have five services, most of which are stateless." },
      { wrong: "The reason why is because…", right: "The reason is that…" },
      { wrong: "the file generating at 23:00", right: "the file generated at 23:00", noteEs: "Voz pasiva → participio de pasado" },
      { wrong: "Running the migration, the DB crashed.", right: "While we were running the migration, …", noteEs: "Dangling participle: el sujeto del participio debe ser el de la principal" },
      { wrong: "the same that before", right: "the same as before" },
      { wrong: "all the which", right: "all of which" },
      { wrong: "This is the man that I spoke with him.", right: "This is the man I spoke with.", noteEs: "Sin pronombre duplicado tras el relativo" },
    ],
    challenges: [
      {
        id: 40,
        instructionsEs:
          "Escribe una descripción completa de tu sistema real en 15 frases.",
        criteria: [
          "15 frases",
          "Cuatro relativas definidas",
          "Tres relativas no definidas con comas correctas",
          "Dos cláusulas de participio reducidas",
          "Una aposición",
          "Un whose",
          "Un which que se refiera a toda la frase anterior",
        ],
        mode: "written",
      },
      {
        id: 41,
        instructionsEs:
          "Oral (4 min): explica esa arquitectura como si la dibujaras en una pizarra en una entrevista de system design. Estructura: \"At a high level, there are three components. The first one, which handles X, …\". Grábate y comprueba si haces las pausas de las comas.",
        criteria: [
          "Duración de unos 4 minutos",
          "Estructura de alto nivel: At a high level, there are three components…",
          "Grabación revisada comprobando las pausas de las comas (relativas no definidas)",
        ],
        mode: "oral",
      },
      {
        id: 42,
        instructionsEs:
          "Coge un párrafo de la documentación en inglés de tu proyecto y reescríbelo reduciendo relativas a participios. Cuenta cuántas palabras ahorras. Suele ser un 15–20%.",
        criteria: [
          "Párrafo real de la documentación del proyecto reescrito",
          "Relativas reducidas a cláusulas de participio",
          "Conteo de palabras ahorradas (referencia: 15–20%)",
        ],
        mode: "real-work",
      },
    ],
    scenarioTypes: ["design_review", "architecture_pitch", "tech_interview"],
  },
];
