/**
 * Ejercicios cerrados (paso Practice) de la Parte 1 (unit 0) y las
 * unidades 1–13 del libro fuente, cruzados con el solucionario del
 * Apéndice I. Transcripción fiel: los retos y producciones libres sin
 * clave cerrada viven en `challenges` de las unidades, no aquí.
 */
import type { UnitExercise } from "@/domain/exercises/exercise";

const NOTA_MODELO = "respuesta modelo; variantes naturales válidas";

export const EXERCISES_P1_U13: UnitExercise[] = [
  // ── PARTE 1 — Sistema de sonidos (unit 0) ────────────────────────────
  {
    id: "P1.5",
    unit: 0,
    kind: "classify",
    promptEs:
      "Clasifica la pronunciación de la terminación -ed de cada verbo: /ɪd/ (sílaba extra, tras /t/ o /d/), /t/ (tras sonido sordo) o /d/ (tras sonido sonoro).",
    items: [
      { stem: "shipped", answer: "/t/" },
      { stem: "migrated", answer: "/ɪd/" },
      { stem: "refactored", answer: "/d/" },
      { stem: "mocked", answer: "/t/" },
      { stem: "deleted", answer: "/ɪd/" },
      { stem: "cached", answer: "/t/" },
      { stem: "rolled", answer: "/d/" },
      { stem: "patched", answer: "/t/" },
      { stem: "committed", answer: "/ɪd/" },
      { stem: "released", answer: "/t/" },
      { stem: "crashed", answer: "/t/" },
      { stem: "debugged", answer: "/d/" },
      { stem: "mounted", answer: "/ɪd/" },
      { stem: "scaled", answer: "/d/" },
      { stem: "wrapped", answer: "/t/" },
    ],
  },
  {
    id: "P1.7",
    unit: 0,
    kind: "choose",
    promptEs:
      "Marca la sílaba fuerte de cada palabra (en la respuesta, la sílaba fuerte va en mayúsculas).",
    items: [
      { stem: "deployment", answer: "dePLOYment" },
      { stem: "configuration", answer: "configuRAtion" },
      { stem: "compatibility", answer: "compatiBIlity" },
      { stem: "refactoring", answer: "reFACtoring" },
      { stem: "dependency", answer: "dePENdency" },
      { stem: "asynchronous", answer: "aSYNchronous" },
      { stem: "repository", answer: "rePOsitory" },
      { stem: "implementation", answer: "implemenTAtion" },
      { stem: "optimization", answer: "optimiZAtion" },
      { stem: "distributed", answer: "disTRIbuted" },
      { stem: "redundancy", answer: "reDUNdancy" },
      { stem: "inheritance", answer: "inHEritance" },
    ],
  },
  {
    id: "P1.10",
    unit: 0,
    kind: "choose",
    promptEs:
      "Sentence stress: frase base «I didn't say the deploy broke it.» Indica qué implica el pico tonal en cada palabra. (En la grabación, las seis versiones deben sonar distintas.)",
    items: [
      { stem: "Énfasis en «I»: I didn't say the deploy broke it.", answer: "Lo dijo otro, no yo" },
      { stem: "Énfasis en «didn't»: I didn't say the deploy broke it.", answer: "Lo niego rotundamente" },
      { stem: "Énfasis en «say»: I didn't say the deploy broke it.", answer: "Lo insinué, no lo dije" },
      { stem: "Énfasis en «the deploy»: I didn't say the deploy broke it.", answer: "Fue otra cosa la que lo rompió" },
      { stem: "Énfasis en «broke»: I didn't say the deploy broke it.", answer: "No se rompió, hizo otra cosa" },
      { stem: "Énfasis en «it»: I didn't say the deploy broke it.", answer: "Rompió otra cosa" },
    ],
  },

  // ── UNIT 1 — Introducing yourself to the team ────────────────────────
  {
    id: "1A",
    unit: 1,
    kind: "fill",
    promptEs: "Completa con la forma correcta de to be.",
    items: [
      { stem: "I ____ a QA engineer.", answer: "am" },
      { stem: "She ____ not on the platform team.", answer: "is" },
      { stem: "____ you the new backend developer?", answer: "Are" },
      { stem: "They ____ in Berlin, but he ____ in Bogotá.", answer: "are, is" },
      { stem: "It ____ my first day.", answer: "is" },
      { stem: "We ____ five hours behind you.", answer: "are" },
      { stem: "____ the tests green?", answer: "Are" },
      { stem: "Priya ____ the tech lead, and Tom and I ____ developers.", answer: "is, are" },
    ],
  },
  {
    id: "1B",
    unit: 1,
    kind: "translate",
    promptEs: "Traduce al inglés. (Cuidado con el sujeto obligatorio y el artículo.)",
    items: [
      { stem: "Soy desarrollador frontend.", answer: "I'm a frontend developer." },
      { stem: "No estoy en el equipo de pagos.", answer: "I'm not on the payments team." },
      { stem: "¿Eres el líder técnico?", answer: "Are you the tech lead?" },
      { stem: "Está roto.", answer: "It's broken." },
      { stem: "Ellos no son de Berlín.", answer: "They're not from Berlin." },
      { stem: "¿Cuántas personas hay en tu equipo? (usa «are on»)", answer: "How many people are on your team?" },
      { stem: "Es mi primer día. Estoy contento de estar aquí.", answer: "It's my first day. I'm glad to be here." },
      { stem: "No estoy seguro. ¿Puedes repetir eso?", answer: "I'm not sure. Could you say that again?" },
    ],
  },
  {
    id: "1C",
    unit: 1,
    kind: "correct",
    promptEs: "Corrige el error. Cada frase tiene exactamente uno.",
    items: [
      { stem: "Is my first sprint.", answer: "It's my first sprint." },
      { stem: "I'm developer.", answer: "I'm a developer." },
      { stem: "Yes, I'm.", answer: "Yes, I am." },
      { stem: "Where you are based?", answer: "Where are you based?" },
      { stem: "I'm in the payments team.", answer: "I'm on the payments team." },
      { stem: "He no is the tech lead.", answer: "He isn't the tech lead." },
      { stem: "Are you a QA engineer? — No, I amn't.", answer: "No, I'm not." },
      { stem: "Nice to meet your.", answer: "Nice to meet you." },
    ],
  },
  {
    id: "1D",
    unit: 1,
    kind: "transform",
    promptEs: "Escribe la pregunta. Te doy la respuesta.",
    items: [
      { stem: "____? — I'm a backend developer.", answer: "What do you do?", altAnswers: ["What's your role?"] },
      { stem: "____? — I'm based in Lima.", answer: "Where are you based?" },
      { stem: "____? — Priya is the tech lead.", answer: "Who's the tech lead?" },
      { stem: "____? — Two weeks. (duración del sprint)", answer: "How long is the sprint?" },
      { stem: "____? — Because the database is down.", answer: "Why is the service down?" },
    ],
  },

  // ── UNIT 2 — Your stack and your working day ─────────────────────────
  {
    id: "2A",
    unit: 2,
    kind: "fill",
    promptEs: "Añade -s solo donde haga falta.",
    items: [
      { stem: "The pipeline run____ every night.", answer: "runs" },
      { stem: "We deploy____ on Tuesdays.", answer: "deploy" },
      { stem: "Does the service restart____ automatically?", answer: "restart" },
      { stem: "He doesn't review____ PRs on Fridays.", answer: "review" },
      { stem: "It try____ three times before it fail____.", answer: "tries, fails" },
      { stem: "Who own____ this repository?", answer: "owns" },
      { stem: "The tests pass____ locally but they fail____ in CI.", answer: "pass, fail" },
      { stem: "She have____ two direct reports. (¡irregular!)", answer: "has" },
    ],
  },
  {
    id: "2B",
    unit: 2,
    kind: "transform",
    promptEs: "Convierte a negativo y a interrogativo.",
    items: [
      { stem: "The build passes.", answer: "The build doesn't pass. / Does the build pass?" },
      { stem: "They deploy on Fridays.", answer: "They don't deploy on Fridays. / Do they deploy on Fridays?" },
      { stem: "It uses Redis.", answer: "It doesn't use Redis. / Does it use Redis?" },
      { stem: "You know Kubernetes.", answer: "You don't know Kubernetes. / Do you know Kubernetes?" },
      { stem: "The PO joins the stand-up.", answer: "The PO doesn't join the stand-up. / Does the PO join the stand-up?" },
    ],
  },
  {
    id: "2C",
    unit: 2,
    kind: "transform",
    promptEs: "Coloca el adverbio.",
    items: [
      { stem: "(usually) The stand-up takes fifteen minutes.", answer: "The stand-up usually takes fifteen minutes." },
      { stem: "(never) We deploy on Fridays.", answer: "We never deploy on Fridays." },
      { stem: "(always) It is slow after a release.", answer: "It is always slow after a release." },
      {
        stem: "(sometimes) The tests fail for no reason.",
        answer: "Sometimes the tests fail for no reason.",
        altAnswers: ["The tests sometimes fail for no reason."],
      },
      { stem: "(twice a week) We release.", answer: "We release twice a week." },
      { stem: "(hardly ever) He answers on Slack.", answer: "He hardly ever answers on Slack." },
    ],
  },
  {
    id: "2D",
    unit: 2,
    kind: "translate",
    promptEs: "Traduce.",
    items: [
      { stem: "¿Cómo funciona el pipeline?", answer: "How does the pipeline work?" },
      { stem: "No usamos Redis; usamos Memcached.", answer: "We don't use Redis; we use Memcached." },
      { stem: "¿Con qué frecuencia despliegas a producción?", answer: "How often do you deploy to production?" },
      { stem: "Nunca desplegamos los viernes.", answer: "We never deploy on Fridays." },
      { stem: "El servicio se reinicia automáticamente cuando falla.", answer: "The service restarts automatically when it fails." },
      { stem: "¿Quién revisa los pull requests?", answer: "Who reviews the pull requests?" },
      { stem: "Normalmente tarda unos diez minutos.", answer: "It usually takes about ten minutes." },
      { stem: "Depende del tamaño del cambio.", answer: "It depends on the size of the change." },
    ],
  },
  {
    id: "2E",
    unit: 2,
    kind: "correct",
    promptEs: "Repaso intercalado (Unidad 1). Corrige.",
    items: [
      { stem: "Is not my responsibility.", answer: "It's not my responsibility." },
      { stem: "I'm agree with Lucas.", answer: "I agree with Lucas." },
      { stem: "Where he is based?", answer: "Where is he based?" },
    ],
  },

  // ── UNIT 3 — Your environment: what exists and where ─────────────────
  {
    id: "3A",
    unit: 3,
    kind: "fill",
    promptEs: "Completa con there is / there are / there isn't / there aren't.",
    items: [
      { stem: "____ two open incidents right now.", answer: "There are" },
      { stem: "____ any documentation for this endpoint?", answer: "Is there" },
      { stem: "____ a workaround, but it's ugly.", answer: "There's" },
      { stem: "____ enough test coverage. We need more.", answer: "There isn't" },
      { stem: "How many services ____ in total?", answer: "are there" },
      { stem: "____ a lot of traffic on Fridays.", answer: "There's" },
      { stem: "Last week ____ an outage. (pasado)", answer: "there was" },
    ],
  },
  {
    id: "3B",
    unit: 3,
    kind: "fill",
    promptEs: "Completa con a, an, the o ∅ (sin artículo).",
    items: [
      { stem: "We found ____ bug. ____ bug only happens on mobile.", answer: "a, The" },
      { stem: "____ microservices are harder than people think.", answer: "∅" },
      { stem: "He's ____ SRE at ____ Amazon.", answer: "an, ∅" },
      { stem: "Can you send me ____ URL?", answer: "the" },
      { stem: "I need ____ hour to finish ____ migration.", answer: "an, the" },
      { stem: "____ documentation is out of date.", answer: "The" },
      { stem: "She wrote ____ script that parses ____ logs.", answer: "a, the" },
      { stem: "This is ____ MVP, not ____ final product.", answer: "an, the" },
      { stem: "I work with ____ Python and ____ Go.", answer: "∅, ∅" },
      { stem: "It's ____ one-line change.", answer: "a" },
    ],
  },
  {
    id: "3C",
    unit: 3,
    kind: "fill",
    promptEs: "Completa con much, many, a few, few, a little, little.",
    items: [
      { stem: "There isn't ____ documentation.", answer: "much" },
      { stem: "There are ____ integration tests — only three, actually. (negativo)", answer: "few" },
      { stem: "We have ____ time left, so let's start. (positivo, algo de)", answer: "a little" },
      { stem: "How ____ services do you own?", answer: "many" },
      { stem: "There were ____ people in the meeting. (unos cuantos)", answer: "a few" },
      { stem: "I don't have ____ experience with Kafka.", answer: "much" },
      { stem: "We have ____ time. We need to cut scope. (negativo, poco)", answer: "little" },
    ],
  },
  {
    id: "3D",
    unit: 3,
    kind: "correct",
    promptEs: "Corrige.",
    items: [
      { stem: "There are a lot of informations in the logs.", answer: "There is a lot of information in the logs." },
      { stem: "I have three feedbacks for you.", answer: "I have three pieces of feedback for you." },
      { stem: "The people is waiting.", answer: "The people are waiting." },
      { stem: "Have two services in production.", answer: "There are two services in production." },
      {
        stem: "I need an advice.",
        answer: "I need some advice.",
        altAnswers: ["I need a piece of advice."],
      },
      { stem: "There is many bugs.", answer: "There are many bugs." },
      { stem: "He gave me some advices about the architecture.", answer: "He gave me some advice about the architecture." },
      { stem: "We use the Python.", answer: "We use Python." },
      { stem: "It's in the main branch. (preposición)", answer: "It's on the main branch." },
      { stem: "The data are corrupted. (uso moderno)", answer: "The data is corrupted." },
    ],
  },
  {
    id: "3E",
    unit: 3,
    kind: "translate",
    promptEs: "Traduce.",
    items: [
      { stem: "Hay tres servicios principales.", answer: "There are three main services." },
      { stem: "No hay documentación para este endpoint.", answer: "There's no documentation for this endpoint." },
      { stem: "¿Cuántas peticiones por segundo hay en el pico?", answer: "How many requests per second are there at peak?" },
      { stem: "Hay muy pocos tests de integración.", answer: "There are very few integration tests." },
      { stem: "La configuración está en el repo, bajo `config/`.", answer: "The configuration is in the repo, under `config/`." },
      { stem: "Los secretos no están en el repo.", answer: "The secrets aren't in the repo." },
      { stem: "Necesito una hora para terminar la migración.", answer: "I need an hour to finish the migration." },
      { stem: "Hay mucho tráfico los viernes.", answer: "There's a lot of traffic on Fridays." },
    ],
  },

  // ── UNIT 4 — What are you working on right now? ──────────────────────
  {
    id: "4A",
    unit: 4,
    kind: "fill",
    promptEs: "Presente simple o continuo.",
    items: [
      { stem: "I usually ____ (start) at 9, but today I ____ (start) at 8 because of the release.", answer: "start, 'm starting" },
      { stem: "The service ____ (run) on port 8080. Right now it ____ (not respond).", answer: "runs, isn't responding" },
      { stem: "What ____ you ____ (work) on this sprint?", answer: "are you working" },
      { stem: "It ____ (depend) on the config.", answer: "depends" },
      { stem: "Sorry, I ____ (not understand) the question.", answer: "don't understand" },
      { stem: "We ____ (deploy) twice a week, but this week we ____ (deploy) three times.", answer: "deploy, 're deploying" },
      {
        stem: "I ____ (see) a lot of timeouts in the logs lately.",
        answer: "'m seeing",
        altAnswers: ["'ve been seeing"],
      },
      { stem: "He ____ (know) Kubernetes very well.", answer: "knows" },
      { stem: "The tests ____ (fail) right now — someone broke `main`.", answer: "are failing" },
      { stem: "Latency ____ (get) worse every week.", answer: "is getting" },
    ],
  },
  {
    id: "4B",
    unit: 4,
    kind: "transform",
    promptEs: "Escribe la forma -ing.",
    items: [
      { stem: "run", answer: "running" },
      { stem: "write", answer: "writing" },
      { stem: "commit", answer: "committing" },
      { stem: "deploy", answer: "deploying" },
      { stem: "merge", answer: "merging" },
      { stem: "get", answer: "getting" },
      { stem: "set", answer: "setting" },
      { stem: "plan", answer: "planning" },
      { stem: "begin", answer: "beginning" },
      { stem: "open", answer: "opening" },
      { stem: "release", answer: "releasing" },
      { stem: "debug", answer: "debugging" },
      { stem: "ship", answer: "shipping" },
      { stem: "update", answer: "updating" },
      { stem: "try", answer: "trying" },
      { stem: "refactor", answer: "refactoring" },
    ],
  },
  {
    id: "4C",
    unit: 4,
    kind: "correct",
    promptEs: "Corrige.",
    items: [
      { stem: "I'm not agree with that approach.", answer: "I don't agree with that approach." },
      { stem: "I'm knowing the answer.", answer: "I know the answer." },
      { stem: "What you are working on?", answer: "What are you working on?" },
      { stem: "He is work on the migration.", answer: "He is working on the migration." },
      { stem: "I'm having a question.", answer: "I have a question." },
      { stem: "This is depending on the load.", answer: "This depends on the load." },
      { stem: "We are deploy tomorrow.", answer: "We're deploying tomorrow." },
      { stem: "I'm needing more context.", answer: "I need more context." },
    ],
  },
  {
    id: "4D",
    unit: 4,
    kind: "translate",
    promptEs: "Traduce.",
    items: [
      { stem: "Estoy investigando el problema del timeout.", answer: "I'm looking into the timeout problem." },
      { stem: "Está tardando más de lo esperado.", answer: "It's taking longer than expected." },
      { stem: "¿En qué estás trabajando ahora mismo?", answer: "What are you working on right now?" },
      { stem: "No lo entiendo. ¿Puedes explicarlo otra vez?", answer: "I don't understand. Could you explain it again?" },
      { stem: "Sigo esperando la aprobación.", answer: "I'm still waiting for approval." },
      { stem: "Está empeorando.", answer: "It's getting worse." },
      { stem: "Estoy atascado en un problema de configuración.", answer: "I'm stuck on a config problem." },
      {
        stem: "Trabajo en el equipo de pagos, pero este sprint estoy ayudando a plataforma.",
        answer: "I work on the payments team, but this sprint I'm helping platform.",
      },
    ],
  },

  // ── UNIT 5 — Asking for things without sounding rude ─────────────────
  {
    id: "5A",
    unit: 5,
    kind: "transform",
    promptEs: "Reescribe estas órdenes como peticiones corteses. Usa una estructura distinta en cada una.",
    items: [
      { stem: "Review my PR.", answer: "Could you review my PR when you get a chance?", noteEs: NOTA_MODELO },
      { stem: "Explain the retry logic.", answer: "Would you mind explaining the retry logic?", noteEs: NOTA_MODELO },
      { stem: "Send me the logs.", answer: "Do you think you could send me the logs?", noteEs: NOTA_MODELO },
      {
        stem: "Give me access to the staging database.",
        answer: "I was wondering if I could get access to the staging database.",
        noteEs: NOTA_MODELO,
      },
      { stem: "Don't merge yet.", answer: "Could you hold off on merging for now?", noteEs: NOTA_MODELO },
      { stem: "Help me with this bug.", answer: "Any chance you could help me with this bug?", noteEs: NOTA_MODELO },
    ],
  },
  {
    id: "5B",
    unit: 5,
    kind: "choose",
    promptEs: "Elige la respuesta correcta.",
    items: [
      {
        stem: "«Would you mind reviewing this?» — Quieres decir que sí ayudas. a) Yes, I would. b) No, not at all. c) Yes, of course.",
        answer: "b",
      },
      {
        stem: "«Do you mind if I merge this?» — Quieres decir que no hay problema. a) No, go ahead. b) Yes, go ahead.",
        answer: "a",
      },
      {
        stem: "«Can I get access?» — Se lo deniegas con cortesía. a) No. b) I'm afraid you'll need approval from Priya first.",
        answer: "b",
      },
    ],
  },
  {
    id: "5C",
    unit: 5,
    kind: "fill",
    promptEs: "Completa con el modal adecuado.",
    items: [
      { stem: "____ you take a look at this when you get a chance?", answer: "Could" },
      { stem: "I ____ reproduce it locally — it only happens in staging.", answer: "can't" },
      { stem: "____ I ask a quick question? (formal)", answer: "May", altAnswers: ["Could"] },
      { stem: "That ____ be great, thanks.", answer: "would" },
      { stem: "You ____ commit secrets to the repo. (prohibición fuerte)", answer: "mustn't" },
      { stem: "You ____ add a test for that edge case. (consejo)", answer: "should" },
      { stem: "It ____ be a caching issue, but I'm not sure. (posibilidad)", answer: "might", altAnswers: ["could"] },
      { stem: "____ we split this into two PRs? (propuesta)", answer: "Shall" },
    ],
  },
  {
    id: "5D",
    unit: 5,
    kind: "correct",
    promptEs: "Corrige.",
    items: [
      { stem: "Can you to review my PR?", answer: "Can you review my PR?" },
      { stem: "He cans help you.", answer: "He can help you." },
      { stem: "Do you can help me?", answer: "Can you help me?" },
      { stem: "Would you mind to explain this?", answer: "Would you mind explaining this?" },
      { stem: "I'm afraid that I can't to do it today.", answer: "I'm afraid I can't do it today." },
      {
        stem: "Please, review my code. (no incorrecto, pero mejorable)",
        answer: "Could you review my code when you get a chance?",
      },
      { stem: "Let's to start.", answer: "Let's start." },
      { stem: "Shall I to roll it back?", answer: "Shall I roll it back?" },
    ],
  },
  {
    id: "5E",
    unit: 5,
    kind: "translate",
    promptEs: "Repaso intercalado (U1–U4). Traduce.",
    items: [
      { stem: "Hay dos tests que fallan ahora mismo.", answer: "There are two tests failing right now." },
      { stem: "No estoy de acuerdo, pero puedo estar equivocado.", answer: "I don't agree, but I could be wrong." },
      { stem: "¿Cuántos servicios tienes en producción?", answer: "How many services do you have in production?" },
      { stem: "Normalmente no despliego los viernes.", answer: "I don't usually deploy on Fridays." },
    ],
  },

  // ── UNIT 6 — What did you do yesterday? ──────────────────────────────
  {
    id: "6A",
    unit: 6,
    kind: "transform",
    promptEs: "Escribe el pasado.",
    items: [
      { stem: "finish", answer: "finished" },
      { stem: "fix", answer: "fixed" },
      { stem: "try", answer: "tried" },
      { stem: "deploy", answer: "deployed" },
      { stem: "stop", answer: "stopped" },
      { stem: "commit", answer: "committed" },
      { stem: "merge", answer: "merged" },
      { stem: "plan", answer: "planned" },
      { stem: "open", answer: "opened" },
      { stem: "happen", answer: "happened" },
      { stem: "run", answer: "ran" },
      { stem: "write", answer: "wrote" },
      { stem: "build", answer: "built" },
      { stem: "break", answer: "broke" },
      { stem: "send", answer: "sent" },
      { stem: "read", answer: "read", noteEs: "se pronuncia /red/" },
      { stem: "think", answer: "thought" },
      { stem: "get", answer: "got" },
      { stem: "make", answer: "made" },
      { stem: "take", answer: "took" },
      { stem: "see", answer: "saw" },
      { stem: "find", answer: "found" },
      { stem: "leave", answer: "left" },
      { stem: "put", answer: "put" },
      { stem: "lose", answer: "lost" },
      { stem: "spend", answer: "spent" },
      { stem: "catch", answer: "caught" },
      { stem: "choose", answer: "chose" },
      { stem: "begin", answer: "began" },
      { stem: "understand", answer: "understood" },
    ],
  },
  {
    id: "6B",
    unit: 6,
    kind: "fill",
    promptEs: "Completa en pasado simple.",
    items: [
      { stem: "Yesterday I ____ (finish) the retry logic and ____ (open) a PR.", answer: "finished, opened" },
      { stem: "Tom ____ (review) it, and I ____ (fix) his comments.", answer: "reviewed, fixed" },
      { stem: "The load test ____ (fail) — the p99 ____ (go) up to four seconds.", answer: "failed, went" },
      { stem: "I ____ (not have) time to investigate.", answer: "didn't have" },
      { stem: "____ you ____ (find) out why?", answer: "Did, find" },
      { stem: "Someone ____ (delete) a production index by mistake.", answer: "deleted" },
      { stem: "It ____ (take) two hours to recover.", answer: "took" },
      { stem: "I ____ (write) the postmortem last night.", answer: "wrote" },
      { stem: "The tests ____ (not pass) in CI, but they ____ (work) locally.", answer: "didn't pass, worked" },
      {
        stem: "____ the database ____ (be) under load at the time?",
        answer: "Was, ∅",
        noteEs: "Was the database under load at the time?",
      },
    ],
  },
  {
    id: "6C",
    unit: 6,
    kind: "correct",
    promptEs: "Corrige.",
    items: [
      { stem: "Did you deployed it?", answer: "Did you deploy it?" },
      { stem: "I didn't wrote the test.", answer: "I didn't write the test." },
      { stem: "He no came to the stand-up.", answer: "He didn't come to the stand-up." },
      { stem: "Yesterday I have finished the PR.", answer: "Yesterday I finished the PR." },
      { stem: "Ago two hours it failed.", answer: "Two hours ago it failed." },
      { stem: "The tests was green.", answer: "The tests were green." },
      { stem: "Who did delete the index?", answer: "Who deleted the index?" },
      { stem: "I was reviewed the PR.", answer: "I reviewed the PR." },
      { stem: "It taked two hours.", answer: "It took two hours." },
      { stem: "Last the week we deployed twice.", answer: "Last week we deployed twice." },
    ],
  },
  {
    id: "6D",
    unit: 6,
    kind: "transform",
    promptEs: "Convierte a negativo y pregunta.",
    items: [
      { stem: "He merged the PR.", answer: "He didn't merge the PR. / Did he merge the PR?" },
      { stem: "It broke the build.", answer: "It didn't break the build. / Did it break the build?" },
      { stem: "They found the root cause.", answer: "They didn't find the root cause. / Did they find the root cause?" },
      { stem: "The pipeline was green.", answer: "The pipeline wasn't green. / Was the pipeline green?" },
      { stem: "We ran the migration.", answer: "We didn't run the migration. / Did we run the migration?" },
    ],
  },
  {
    id: "6E",
    unit: 6,
    kind: "translate",
    promptEs: "Traduce.",
    items: [
      { stem: "Ayer terminé la lógica de reintentos y abrí un PR.", answer: "Yesterday I finished the retry logic and opened a PR." },
      { stem: "No tuve tiempo de investigarlo.", answer: "I didn't have time to look into it." },
      { stem: "¿Encontraste la causa raíz?", answer: "Did you find the root cause?" },
      { stem: "Alguien borró un índice de producción sin querer.", answer: "Someone deleted a production index by mistake." },
      { stem: "Tardó dos horas en recuperarse.", answer: "It took two hours to recover." },
      { stem: "Los tests no pasaron en CI, pero funcionaban en local.", answer: "The tests didn't pass in CI, but they worked locally." },
      { stem: "Resultó ser un problema de configuración.", answer: "It turned out to be a config issue." },
      { stem: "Hace dos horas el servicio estaba caído.", answer: "Two hours ago the service was down." },
    ],
  },

  // ── UNIT 7 — The complete stand-up ───────────────────────────────────
  {
    id: "7A",
    unit: 7,
    kind: "fill",
    promptEs: "Completa con going to, presente continuo o will.",
    items: [
      { stem: "Today I ____ (start) on the migration. (intención decidida)", answer: "'m going to start" },
      { stem: "— The build is red. — OK, I ____ (take) a look right now. (decisión inmediata)", answer: "'ll take" },
      { stem: "We ____ (deploy) at 4 p.m. It's on the calendar.", answer: "'re deploying" },
      { stem: "Look at the memory graph — it ____ (crash).", answer: "'s going to crash" },
      { stem: "I think it ____ (be) a config issue, but I'm not sure.", answer: "will be" },
      { stem: "I ____ (meet) the security team tomorrow at ten.", answer: "'m meeting" },
      { stem: "If the test fails again, I ____ (revert) it.", answer: "'ll revert" },
    ],
  },
  {
    id: "7B",
    unit: 7,
    kind: "order",
    promptEs:
      "Ordena este stand-up desordenado. Indica la posición (1–4) de cada frase. Orden correcto: c → d → b → a.",
    items: [
      { stem: "a) No blockers, but I might need Maya for a review.", answer: "4" },
      { stem: "b) Today I'm going to add the integration tests.", answer: "3" },
      { stem: "c) Yesterday I finished the parser and opened a PR.", answer: "1" },
      { stem: "d) I also spent an hour on the flaky test but I didn't get to the bottom of it.", answer: "2" },
    ],
  },
  {
    id: "7C",
    unit: 7,
    kind: "translate",
    promptEs: "Traduce.",
    items: [
      { stem: "Ayer terminé la migración y conseguí que se fusionara.", answer: "Yesterday I finished the migration and got it merged." },
      { stem: "Hoy voy a empezar con el script de backfill.", answer: "Today I'm going to start on the backfill script." },
      { stem: "Mi objetivo es tener un borrador para el final del día.", answer: "My goal is to have a draft by the end of the day." },
      { stem: "Estoy bloqueado: necesito acceso a los dashboards de producción.", answer: "I'm blocked: I need access to the production dashboards." },
      { stem: "No estoy bloqueado, pero puede que necesite a Tom media hora más tarde.", answer: "I'm not blocked, but I might need Tom half an hour later." },
      { stem: "Si eso no funciona, probaré con un test de carga en local.", answer: "If that doesn't work, I'll try a load test locally." },
      { stem: "Pasé casi todo el día en el incidente.", answer: "I spent most of the day on the incident." },
      { stem: "¿Podemos hablarlo después de la reunión?", answer: "Can we talk about it after the meeting?" },
    ],
  },

  // ── UNIT 8 — Comparing technologies and options ──────────────────────
  {
    id: "8A",
    unit: 8,
    kind: "fill",
    promptEs: "Comparativo o superlativo.",
    items: [
      { stem: "Postgres is ____ (simple) than DynamoDB to operate.", answer: "simpler" },
      { stem: "This is ____ (bad) outage we've had this year.", answer: "the worst" },
      { stem: "gRPC is ____ (fast) than REST, but it's ____ (hard) to debug.", answer: "faster, harder" },
      { stem: "It's one of ____ (common) mistakes in distributed systems.", answer: "the most common" },
      { stem: "Kafka is ____ (reliable) than what we had before.", answer: "more reliable" },
      { stem: "That's ____ (good) approach, but it's also ____ (expensive).", answer: "a better, more expensive" },
      { stem: "This test is ____ (flaky) than the other one.", answer: "flakier" },
      { stem: "The ____ (little) risky option is usually the boring one.", answer: "least" },
    ],
  },
  {
    id: "8B",
    unit: 8,
    kind: "fill",
    promptEs: "Añade el modificador correcto (much, slightly, twice as, far, too, enough).",
    items: [
      { stem: "It's ____ more expensive — about 3x the cost.", answer: "much", altAnswers: ["far"] },
      { stem: "It's ____ slower, maybe 5%.", answer: "slightly" },
      { stem: "It's ____ fast ____ Redis. (el doble de rápido)", answer: "twice as fast as" },
      { stem: "Postgres is fast ____ for our volume.", answer: "enough" },
      { stem: "Microservices would be ____ risky for a team of four.", answer: "too" },
    ],
  },
  {
    id: "8C",
    unit: 8,
    kind: "correct",
    promptEs: "Corrige.",
    items: [
      { stem: "It's more better.", answer: "It's much better." },
      { stem: "Postgres is more simple than Mongo.", answer: "Postgres is simpler than Mongo." },
      { stem: "It's more faster that the old one.", answer: "It's faster than the old one." },
      { stem: "It's very faster.", answer: "It's much faster." },
      { stem: "It's the most fast option.", answer: "It's the fastest option." },
      {
        stem: "This approach is different than the previous one.",
        answer: "This approach is different from the previous one.",
        altAnswers: ["This approach is different to the previous one."],
      },
      { stem: "It's not so flexible as SQL.", answer: "It's not as flexible as SQL." },
      { stem: "I'd rather to use Postgres.", answer: "I'd rather use Postgres." },
      { stem: "It's one of the most common mistake.", answer: "It's one of the most common mistakes." },
      { stem: "It's enough fast.", answer: "It's fast enough." },
    ],
  },
  {
    id: "8D",
    unit: 8,
    kind: "translate",
    promptEs: "Traduce.",
    items: [
      {
        stem: "Postgres es más simple de operar, pero DynamoDB es más rápido para este patrón de acceso.",
        answer: "Postgres is simpler to operate, but DynamoDB is faster for this access pattern.",
      },
      { stem: "Es bastante más caro con nuestro volumen.", answer: "It's considerably more expensive at our volume." },
      { stem: "El problema mayor es que es mucho menos flexible.", answer: "The bigger problem is that it's much less flexible." },
      { stem: "¿Cuánto más rápido es? ¿El doble o diez veces?", answer: "How much faster is it? Twice, or ten times?" },
      { stem: "Postgres es suficientemente rápido para lo que necesitamos.", answer: "Postgres is fast enough for what we need." },
      {
        stem: "La opción menos arriesgada suele ser la que el equipo ya conoce.",
        answer: "The least risky option is usually the one the team already knows.",
      },
      {
        stem: "Preferiría un sistema algo más lento que podamos depurar.",
        answer: "I'd rather have a slightly slower system that we can debug.",
      },
      {
        stem: "El compromiso es simplicidad operativa frente a latencia pura.",
        answer: "The trade-off is operational simplicity versus raw latency.",
      },
    ],
  },

  // ── UNIT 9 — Estimates, plans and promises ───────────────────────────
  {
    id: "9A",
    unit: 9,
    kind: "fill",
    promptEs: "Completa con will, going to o presente continuo.",
    items: [
      { stem: "— The pipeline is red. — I ____ (check) it right now.", answer: "'ll check" },
      { stem: "I ____ (start) the migration tomorrow. I decided yesterday.", answer: "'m going to start" },
      { stem: "We ____ (have) a retro on Friday at 3. It's on the calendar.", answer: "'re having" },
      { stem: "Look at the disk usage — it ____ (run out) tonight.", answer: "'s going to run out" },
      { stem: "I think this approach ____ (be) easier to maintain.", answer: "will be" },
      { stem: "I promise I ____ (not merge) without a review.", answer: "won't merge" },
    ],
  },
  {
    id: "9B",
    unit: 9,
    kind: "fill",
    promptEs: "Presente o will.",
    items: [
      { stem: "I'll merge it as soon as the tests ____ (pass).", answer: "pass" },
      { stem: "When you ____ (finish), let me know and I ____ (deploy) it.", answer: "finish, 'll deploy" },
      { stem: "I won't release until Priya ____ (approve) it.", answer: "approves" },
      { stem: "By the time we ____ (be) done, it ____ (be) midnight.", answer: "are, 'll be" },
      { stem: "Once the migration ____ (be) complete, we ____ (delete) the old table.", answer: "is, 'll delete" },
      { stem: "If it ____ (take) longer than a week, we ____ (split) it.", answer: "takes, 'll split" },
    ],
  },
  {
    id: "9C",
    unit: 9,
    kind: "transform",
    promptEs: "Reescribe con hedging. Suaviza estas afirmaciones demasiado rotundas.",
    items: [
      {
        stem: "It will take three days.",
        answer: "It'll probably take about three days, though I'd want to check the data volume first.",
        noteEs: NOTA_MODELO,
      },
      { stem: "It will work.", answer: "It should work, as far as I can tell.", noteEs: NOTA_MODELO },
      { stem: "That's wrong.", answer: "I'm not sure that's quite right.", noteEs: NOTA_MODELO },
      {
        stem: "We can't do it this sprint.",
        answer: "I don't think we've got the capacity this sprint.",
        noteEs: NOTA_MODELO,
      },
      {
        stem: "The bug is in the cache layer.",
        answer: "My best guess is the cache layer, but I haven't confirmed it.",
        noteEs: NOTA_MODELO,
      },
    ],
  },
  {
    id: "9D",
    unit: 9,
    kind: "correct",
    promptEs: "Corrige.",
    items: [
      { stem: "I will tell you when I will know.", answer: "I'll tell you when I know." },
      { stem: "If it will fail, we revert.", answer: "If it fails, we'll revert." },
      { stem: "I'm going to check it right now. (alguien te lo acaba de pedir)", answer: "OK, I'll check it right now." },
      { stem: "Unless the tests don't pass, I won't merge.", answer: "Unless the tests pass, I won't merge." },
      { stem: "I won't to do it.", answer: "I won't do it." },
      { stem: "When I will finish, I'll ping you.", answer: "When I finish, I'll ping you." },
      { stem: "It's going to take probably three days. (orden del adverbio)", answer: "It's probably going to take three days." },
      { stem: "I'll can do it tomorrow.", answer: "I'll be able to do it tomorrow." },
    ],
  },
  {
    id: "9E",
    unit: 9,
    kind: "translate",
    promptEs: "Traduce.",
    items: [
      { stem: "Sinceramente, es difícil decirlo.", answer: "Honestly, it's hard to say." },
      { stem: "Si todo va bien, diría tres días.", answer: "If all goes well, I'd say three days." },
      { stem: "Hay riesgo de que el backfill tarde más.", answer: "There's a risk the backfill takes longer." },
      { stem: "No lo sabré hasta que lo pruebe con volúmenes reales.", answer: "I won't know until I've tried it at realistic volumes." },
      { stem: "¿Puedes darme un rango? — De tres a cinco días.", answer: "Can you give me a range? — Three to five days." },
      {
        stem: "Tendré una estimación mucho mejor cuando lo haya ejecutado contra una copia de producción.",
        answer: "I'll have a much better estimate once I've run it against a production copy.",
      },
      { stem: "En cuanto esté listo, ejecutaré la primera pasada.", answer: "As soon as it's ready, I'll run the first pass." },
      { stem: "Puede que me equivoque, pero creo que es la opción más segura.", answer: "I might be wrong, but I think it's the safer option." },
    ],
  },

  // ── UNIT 10 — Your experience: present perfect vs past simple ────────
  {
    id: "10A",
    unit: 10,
    kind: "fill",
    promptEs: "Presente perfecto o pasado simple.",
    items: [
      { stem: "I ____ (work) with Kafka, but not in production.", answer: "'ve worked" },
      { stem: "I ____ (lead) the payments migration in 2024.", answer: "led" },
      { stem: "____ you ever ____ (be) on call?", answer: "Have, been" },
      { stem: "He ____ (join) the team in March.", answer: "joined" },
      { stem: "He ____ (be) on the team since March.", answer: "'s been" },
      { stem: "We ____ (not deploy) since Tuesday.", answer: "haven't deployed" },
      { stem: "____ you ____ (finish) the review yet?", answer: "Have, finished" },
      { stem: "I ____ (see) this error twice this week.", answer: "'ve seen" },
      { stem: "The build ____ (fail) five minutes ago.", answer: "failed" },
      { stem: "The build ____ (fail) — someone needs to look at it.", answer: "has failed" },
      { stem: "How long ____ you ____ (be) at this company?", answer: "have, been" },
      { stem: "When ____ you ____ (start) here?", answer: "did, start" },
    ],
  },
  {
    id: "10B",
    unit: 10,
    kind: "fill",
    promptEs: "Completa con for o since.",
    items: [
      { stem: "I've been here ____ three years.", answer: "for" },
      { stem: "I've been here ____ 2023.", answer: "since" },
      { stem: "We haven't released ____ last Thursday.", answer: "since" },
      { stem: "It's been failing ____ a couple of weeks.", answer: "for" },
      { stem: "I've known him ____ we worked together at my last job.", answer: "since" },
      { stem: "The service has been down ____ twenty minutes.", answer: "for" },
      { stem: "Nothing has changed ____ the last deploy.", answer: "since" },
    ],
  },
  {
    id: "10C",
    unit: 10,
    kind: "fill",
    promptEs: "Coloca el adverbio (ever, never, just, already, yet, still).",
    items: [
      { stem: "I've ____ deployed it — it should be live in a minute.", answer: "just" },
      { stem: "Have you ____ used Rust?", answer: "ever" },
      { stem: "I haven't finished ____.", answer: "yet" },
      { stem: "I've ____ reviewed it, you can merge.", answer: "already" },
      { stem: "I've ____ seen a failure like this before. (nunca)", answer: "never" },
      { stem: "I ____ haven't heard back from the platform team.", answer: "still" },
    ],
  },
  {
    id: "10D",
    unit: 10,
    kind: "fill",
    promptEs: "Presente perfecto simple o continuo.",
    items: [
      { stem: "I ____ (debug) this for three hours and I ____ (not find) the cause.", answer: "'ve been debugging, haven't found" },
      { stem: "She ____ (write) the docs all morning.", answer: "'s been writing" },
      { stem: "We ____ (fix) six bugs this sprint.", answer: "'ve fixed" },
      { stem: "I ____ (know) him for years.", answer: "'ve known" },
      { stem: "Sorry, I ____ (run) load tests — that's why staging is slow.", answer: "'ve been running" },
    ],
  },
  {
    id: "10E",
    unit: 10,
    kind: "correct",
    promptEs: "Corrige. (Todos son errores reales de hispanohablantes.)",
    items: [
      { stem: "I work here since 2023.", answer: "I've worked here since 2023." },
      { stem: "I'm working here for three years.", answer: "I've been working here for three years." },
      {
        stem: "I have 5 years of experience working with Java. (no es incorrecto, pero mejóralo)",
        answer: "I've been working with Java for five years.",
      },
      { stem: "Since three years I'm using Go.", answer: "I've been using Go for three years." },
      { stem: "Have you ever went to a conference?", answer: "Have you ever been to a conference?" },
      { stem: "I've saw this before.", answer: "I've seen this before." },
      {
        stem: "I've never used it before, no?",
        answer: "I've never used it before, have I?",
        altAnswers: ["I've never used it before, right?"],
      },
      { stem: "How long time are you here?", answer: "How long have you been here?" },
      { stem: "He has joined the team last March.", answer: "He joined the team last March." },
      { stem: "I didn't finish yet.", answer: "I haven't finished yet." },
      { stem: "I've been knowing him for years.", answer: "I've known him for years." },
      { stem: "We have deployed it yesterday.", answer: "We deployed it yesterday." },
    ],
  },
  {
    id: "10F",
    unit: 10,
    kind: "translate",
    promptEs: "Traduce. (Cuidado: el español usa presente donde el inglés usa perfecto.)",
    items: [
      { stem: "Llevo seis años como desarrollador backend.", answer: "I've been a backend developer for six years." },
      { stem: "Trabajo aquí desde 2023.", answer: "I've worked here since 2023." },
      { stem: "Llevo tres horas depurando esto.", answer: "I've been debugging this for three hours." },
      { stem: "Nunca lo he usado en producción.", answer: "I've never used it in production." },
      { stem: "¿Has liderado algún proyecto alguna vez?", answer: "Have you ever led a project?" },
      { stem: "He gestionado unos quince incidentes.", answer: "I've handled around fifteen incidents." },
      { stem: "No hemos desplegado desde el jueves.", answer: "We haven't deployed since Thursday." },
      { stem: "Es la primera vez que veo ese error.", answer: "It's the first time I've seen that error." },
      { stem: "Acabo de subir un arreglo.", answer: "I've just pushed a fix." },
      {
        stem: "Todavía no he recibido respuesta del equipo de plataforma.",
        answer: "I still haven't heard back from the platform team.",
      },
    ],
  },

  // ── UNIT 11 — Writing instructions and documentation ─────────────────
  {
    id: "11A",
    unit: 11,
    kind: "transform",
    promptEs: "Convierte a imperativo.",
    items: [
      { stem: "You have to clone the repository.", answer: "Clone the repository." },
      { stem: "It's necessary to copy the env file.", answer: "Copy the env file." },
      {
        stem: "The user should not commit secrets.",
        answer: "Do not commit secrets.",
        altAnswers: ["Never commit secrets."],
      },
      {
        stem: "You need to run the migrations before starting the server.",
        answer: "Run the migrations before starting the server.",
      },
    ],
  },
  {
    id: "11B",
    unit: 11,
    kind: "transform",
    promptEs: "Activa a pasiva.",
    items: [
      {
        stem: "The system validates the token.",
        answer: "The token is validated.",
        noteEs:
          "errata del libro: el solucionario imprime «It is deployed nightly.», que no corresponde a este enunciado; se da la pasiva del enunciado",
      },
      { stem: "Someone deleted the production index.", answer: "The production index was deleted." },
      { stem: "We store secrets in Vault.", answer: "Secrets are stored in Vault." },
      { stem: "You must approve every PR.", answer: "Every PR must be approved." },
      { stem: "The pipeline runs the tests automatically.", answer: "The tests are run automatically." },
    ],
  },
  {
    id: "11C",
    unit: 11,
    kind: "fill",
    promptEs: "Completa con must, mustn't, don't have to o should.",
    items: [
      { stem: "You ____ commit the `.env` file. (prohibido)", answer: "mustn't" },
      { stem: "You ____ restart the server — it reloads automatically. (no es necesario)", answer: "don't have to" },
      { stem: "All requests ____ include an auth token. (obligatorio)", answer: "must" },
      { stem: "You ____ run the tests locally first. (recomendado)", answer: "should" },
      { stem: "You ____ use `--force` unless you know what you're doing. (no recomendado)", answer: "shouldn't" },
    ],
  },
  {
    id: "11D",
    unit: 11,
    kind: "correct",
    promptEs: "Corrige los conectores.",
    items: [
      { stem: "At the end, restart the service.", answer: "Finally, restart the service." },
      { stem: "Actually, install the dependencies.", answer: "First, install the dependencies." },
      { stem: "After to run the migration, start the server.", answer: "After running the migration, start the server." },
      { stem: "In the other hand, you can use the CLI.", answer: "On the other hand, you can use the CLI." },
      {
        stem: "Make sure to have Docker installed.",
        answer: "Make sure you have Docker installed.",
        altAnswers: ["Make sure Docker is installed."],
      },
      {
        stem: "Take in account that this takes two minutes.",
        answer: "Take into account that this takes two minutes.",
        altAnswers: ["Bear in mind that this takes two minutes."],
      },
      { stem: "For finish, run the smoke tests.", answer: "Finally, run the smoke tests." },
      { stem: "Before to deploy, check the rollback plan.", answer: "Before deploying, check the rollback plan." },
    ],
  },
  {
    id: "11E",
    unit: 11,
    kind: "translate",
    promptEs: "Traduce (registro de documentación).",
    items: [
      {
        stem: "Antes de empezar, asegúrate de tener Docker 24 o superior instalado.",
        answer: "Before you start, make sure you have Docker 24 or later installed.",
      },
      {
        stem: "Copia `.env.example` a `.env` y rellena los valores. No subas este archivo al repositorio.",
        answer: "Copy `.env.example` to `.env` and fill in the values. Do not commit this file.",
      },
      {
        stem: "Una vez que los contenedores estén sanos, ejecuta las migraciones.",
        answer: "Once the containers are healthy, run the migrations.",
      },
      { stem: "Los secretos se almacenan en Vault, no en el repositorio.", answer: "Secrets are stored in Vault, not in the repository." },
      {
        stem: "Los datos de prueba se generan automáticamente la primera vez que ejecutas la app.",
        answer: "Test data is generated automatically the first time you run the app.",
      },
      {
        stem: "Si las migraciones fallan con un error de conexión, comprueba que Postgres esté ejecutándose.",
        answer: "If the migrations fail with a connection error, check that Postgres is running.",
      },
      { stem: "La causa más habitual es un conflicto de puertos.", answer: "The most common cause is a port conflict." },
      {
        stem: "Esto puede tardar hasta dos minutos, así que ten paciencia.",
        answer: "This can take up to two minutes, so be patient.",
      },
    ],
  },

  // ── UNIT 12 — Narrating a bug ────────────────────────────────────────
  {
    id: "12A",
    unit: 12,
    kind: "fill",
    promptEs: "Pasado simple o pasado continuo.",
    items: [
      { stem: "We ____ (run) the batch job when the database ____ (run out) of connections.", answer: "were running, ran out" },
      { stem: "While the job ____ (process) records, the API ____ (start) timing out.", answer: "was processing, started" },
      { stem: "I ____ (not look) at the dashboards when the alert ____ (fire).", answer: "wasn't looking, fired" },
      { stem: "What ____ you ____ (do) when it ____ (crash)?", answer: "were you doing, crashed" },
      { stem: "Someone ____ (run) a manual backfill in another session.", answer: "was running" },
      { stem: "By the time I ____ (check), the pool ____ (already be) saturated.", answer: "checked, had already been" },
      { stem: "He ____ (review) the PR while I ____ (write) the tests.", answer: "was reviewing, was writing" },
    ],
  },
  {
    id: "12B",
    unit: 12,
    kind: "fill",
    promptEs: "Completa con used to, would, usually o presente simple.",
    items: [
      { stem: "We ____ have an alert for that, but we removed it.", answer: "used to" },
      { stem: "I ____ deploy on Tuesdays. (hábito actual)", answer: "usually" },
      { stem: "Every Friday we ____ freeze the release. (hábito pasado repetido)", answer: "would" },
      { stem: "____ you ____ run the migration manually? (pregunta sobre el pasado)", answer: "Did, use to" },
      { stem: "We ____ deploy on Fridays. (pasado, ya no) — negativo", answer: "didn't use to" },
      { stem: "I ____ be a QA engineer before I moved to backend.", answer: "used to" },
    ],
  },
  {
    id: "12C",
    unit: 12,
    kind: "correct",
    promptEs: "Corrige.",
    items: [
      { stem: "I was checking the logs when it was crashing.", answer: "I was checking the logs when it crashed." },
      { stem: "We used to had an alert.", answer: "We used to have an alert." },
      { stem: "Did you used to deploy manually?", answer: "Did you use to deploy manually?" },
      { stem: "I use to deploy on Tuesdays. (hábito actual)", answer: "I usually deploy on Tuesdays." },
      { stem: "While I debugged, it crashed.", answer: "While I was debugging, it crashed." },
      { stem: "We didn't used to have monitoring.", answer: "We didn't use to have monitoring." },
      { stem: "I was wanting to ask about that.", answer: "I wanted to ask about that." },
      { stem: "When the alert fired, I was checked the logs.", answer: "When the alert fired, I was checking the logs." },
    ],
  },
  {
    id: "12D",
    unit: 12,
    kind: "translate",
    promptEs: "Traduce.",
    items: [
      {
        stem: "Estábamos ejecutando el batch cuando la base de datos se quedó sin conexiones.",
        answer: "We were running the batch job when the database ran out of connections.",
      },
      { stem: "Mientras se ejecutaba, la API empezó a dar timeouts.", answer: "While it was running, the API started timing out." },
      { stem: "¿Estaba pasando algo más al mismo tiempo?", answer: "Was anything else going on at the same time?" },
      { stem: "No estaba mirando los dashboards, la verdad.", answer: "I wasn't looking at the dashboards, to be honest." },
      { stem: "Cuando fui a comprobarlo, el pool ya estaba saturado.", answer: "By the time I checked, the pool was already saturated." },
      { stem: "Antes teníamos una alerta para eso.", answer: "We used to have an alert for that." },
      { stem: "Se eliminó porque era demasiado ruidosa.", answer: "It was removed because it was too noisy." },
      { stem: "Solíamos recibir unos veinte falsos positivos por semana.", answer: "We used to get about twenty false positives a week." },
    ],
  },
  {
    id: "12E",
    unit: 12,
    kind: "correct",
    promptEs: "Repaso intercalado (U7–U11). Corrige.",
    items: [
      { stem: "If the tests will pass, I will merge it.", answer: "If the tests pass, I'll merge it." },
      { stem: "I work here since three years.", answer: "I've worked here for three years." },
      { stem: "It's more simple than the alternative.", answer: "It's simpler than the alternative." },
      { stem: "At the end, restart the service.", answer: "Finally, restart the service." },
      { stem: "Would you mind to take a look?", answer: "Would you mind taking a look?" },
    ],
  },

  // ── UNIT 13 — Code review without making enemies ─────────────────────
  {
    id: "13A",
    unit: 13,
    kind: "transform",
    promptEs:
      "Reescribe estos comentarios de code review de forma aceptable. Usa un suavizador de apertura, uno de intensidad y uno de cierre en cada uno.",
    items: [
      {
        stem: "This is wrong.",
        answer: "I might be missing something, but I don't think this handles the case where the list is empty.",
        noteEs: NOTA_MODELO,
      },
      {
        stem: "You didn't handle the null case.",
        answer: "Question: is the null case reachable here? If so, this would throw.",
        noteEs: NOTA_MODELO,
      },
      {
        stem: "Why didn't you use a map here?",
        answer: "Have you considered a map? It'd avoid the nested loop — though happy to leave it if there's a reason.",
        noteEs: NOTA_MODELO,
      },
      {
        stem: "This won't scale.",
        answer: "This is the one I'd want to flag: at 10k rows this becomes O(n²). Not blocking for now, but worth a ticket.",
        noteEs: NOTA_MODELO,
      },
      {
        stem: "Remove this comment, it's useless.",
        answer: "nit: I think this comment can go — the code says the same thing.",
        noteEs: NOTA_MODELO,
      },
      {
        stem: "You need a test for this.",
        answer: "Could we add a test for this path? Blocking, I'm afraid, since it's the failure case.",
        noteEs: NOTA_MODELO,
      },
    ],
  },
  {
    id: "13B",
    unit: 13,
    kind: "transform",
    promptEs: "Convierte a pregunta indirecta.",
    items: [
      { stem: "Why did you choose Kafka?", answer: "Could I ask why you chose Kafka?" },
      { stem: "Where is the retry logic?", answer: "Do you know where the retry logic is?" },
      { stem: "Does it handle empty lists?", answer: "Do you know whether it handles empty lists?" },
      { stem: "Did you run the load test?", answer: "Could you tell me if you ran the load test?" },
      { stem: "What does this flag do?", answer: "I was wondering what this flag does." },
      { stem: "How long will the migration take?", answer: "Do you have any idea how long the migration will take?" },
    ],
  },
  {
    id: "13C",
    unit: 13,
    kind: "choose",
    promptEs: "Elige el modal correcto.",
    items: [
      { stem: "It ____ be a caching issue — nothing else changed. (deducción segura)", answer: "must" },
      { stem: "It ____ be the network; the other calls work fine. (imposibilidad deducida)", answer: "can't" },
      { stem: "Someone ____ changed the config last night. (deducción sobre el pasado)", answer: "must have" },
      { stem: "We ____ caught this in review. (crítica: no lo hicimos y deberíamos)", answer: "should have" },
      { stem: "It ____ be a race condition, but I'm not sure. (posibilidad)", answer: "might", altAnswers: ["could"] },
      { stem: "It ____ have been the migration — that ran on Tuesday. (imposibilidad pasada)", answer: "can't" },
    ],
  },
  {
    id: "13D",
    unit: 13,
    kind: "correct",
    promptEs: "Corrige.",
    items: [
      { stem: "I was wondering why did you do it like this.", answer: "I was wondering why you did it like this." },
      { stem: "Do you know where is the config file?", answer: "Do you know where the config file is?" },
      { stem: "This could of been avoided.", answer: "This could have been avoided." },
      { stem: "It mustn't be the network.", answer: "It can't be the network." },
      { stem: "You should to add a test.", answer: "You should add a test." },
      { stem: "Could you tell me what does this flag do?", answer: "Could you tell me what this flag does?" },
      { stem: "I'm not agree with this approach.", answer: "I don't agree with this approach." },
      {
        stem: "This is very bad code.",
        answer: "I think there's a cleaner way to do this — mind if I suggest one?",
        noteEs: NOTA_MODELO,
      },
    ],
  },
  {
    id: "13E",
    unit: 13,
    kind: "translate",
    promptEs: "Traduce, ajustando el registro al de un code review anglosajón.",
    items: [
      {
        stem: "Puede que se me esté escapando algo, pero parece que `retryCount` no se reinicia entre llamadas.",
        answer: "I might be missing something, but it looks like `retryCount` isn't reset between calls.",
      },
      {
        stem: "¿No significaría eso que la tercera llamada falla inmediatamente?",
        answer: "Wouldn't that mean the third call fails immediately?",
      },
      {
        stem: "Detalle menor: ¿podríamos sacar el timeout a configuración en lugar de dejarlo fijo en el código?",
        answer: "nit: could we pull the timeout out into config rather than hard-coding it?",
      },
      { stem: "Este punto sí me preocupa algo más.", answer: "This one I'm a bit more concerned about." },
      {
        stem: "Tragarse la excepción aquí significa que perderíamos toda visibilidad.",
        answer: "Swallowing the exception here means we'd lose all visibility.",
      },
      { stem: "¿Podríamos al menos registrarlo a nivel de warning?", answer: "Could we at least log it at warning level?" },
      { stem: "Por lo demás, no es bloqueante.", answer: "Other than that, it's not blocking." },
      { stem: "Buena observación — tienes razón, eso es un bug.", answer: "Good catch — you're right, that's a bug." },
    ],
  },
];
