/**
 * Apéndice C — Colocaciones técnicas (150).
 * Transcripción fiel del libro fuente. Categorías C.1–C.7:
 * codigo, tests-ci, deploy-operacion, incidentes, arquitectura-datos,
 * trabajo-proceso y verbos-frecuentes (verbo + objetos naturales).
 */
import type { Collocation } from "@/domain/reference/reference";

const C1 = "C.1-codigo";
const C2 = "C.2-tests-ci";
const C3 = "C.3-deploy-operacion";
const C4 = "C.4-incidentes";
const C5 = "C.5-arquitectura-datos";
const C6 = "C.6-trabajo-proceso";
const C7 = "C.7-verbos-frecuentes";

export const COLLOCATIONS: Collocation[] = [
  // C.1 · Código
  { text: "write code", category: C1 },
  { text: "refactor a module", category: C1 },
  { text: "review a PR", category: C1 },
  { text: "open / close a PR", category: C1 },
  { text: "leave a comment", category: C1 },
  { text: "address a comment", category: C1 },
  { text: "resolve a conflict", category: C1 },
  { text: "rebase onto main", category: C1 },
  { text: "squash commits", category: C1 },
  { text: "cherry-pick a commit", category: C1 },
  { text: "revert a commit", category: C1 },
  { text: "push to a branch", category: C1 },
  { text: "merge a branch", category: C1 },
  { text: "cut a branch", category: C1 },
  { text: "raise an exception", category: C1 },
  { text: "catch an exception", category: C1 },
  { text: "throw an error", category: C1 },
  { text: "swallow an error", category: C1 },
  { text: "handle an edge case", category: C1 },
  { text: "cover an edge case", category: C1 },
  { text: "meet a requirement", category: C1 },
  { text: "break backwards compatibility", category: C1 },
  { text: "introduce a regression", category: C1 },
  { text: "fix a bug", category: C1 },
  { text: "reproduce a bug", category: C1 },
  { text: "triage a bug", category: C1 },
  { text: "close a ticket", category: C1 },
  { text: "pick up a ticket", category: C1 },
  { text: "pay down tech debt", category: C1 },
  { text: "accrue tech debt", category: C1 },
  { text: "hard-code a value", category: C1 },
  { text: "extract a constant", category: C1 },
  { text: "enforce a convention", category: C1 },
  { text: "follow a convention", category: C1 },

  // C.2 · Tests y CI
  { text: "run the tests", category: C2 },
  { text: "write a test", category: C2 },
  { text: "a test passes / fails", category: C2 },
  { text: "a flaky test", category: C2 },
  { text: "increase coverage", category: C2 },
  { text: "mock a dependency", category: C2 },
  { text: "stub a response", category: C2 },
  { text: "assert on a value", category: C2 },
  { text: "the build is green / red", category: C2 },
  { text: "break the build", category: C2 },
  { text: "the pipeline is stuck", category: C2 },
  { text: "trigger a build", category: C2 },
  { text: "a smoke test", category: C2 },
  { text: "an integration test", category: C2 },
  { text: "load-test a service", category: C2 },
  { text: "benchmark a change", category: C2 },

  // C.3 · Deploy y operación
  { text: "ship a feature", category: C3 },
  { text: "cut a release", category: C3 },
  { text: "tag a version", category: C3 },
  { text: "bump the version", category: C3 },
  { text: "deploy to staging", category: C3 },
  { text: "promote to production", category: C3 },
  { text: "roll out gradually", category: C3 },
  { text: "roll back a release", category: C3 },
  { text: "flip a feature flag", category: C3 },
  { text: "dark-launch a feature", category: C3 },
  { text: "take a service down", category: C3 },
  { text: "bring a service up", category: C3 },
  { text: "drain traffic", category: C3 },
  { text: "shift traffic", category: C3 },
  { text: "scale horizontally", category: C3 },
  { text: "provision a node", category: C3 },
  { text: "rotate a secret", category: C3 },
  { text: "revoke a token", category: C3 },
  { text: "apply a migration", category: C3 },
  { text: "back out a migration", category: C3 },

  // C.4 · Incidentes
  { text: "an alert fires", category: C4 },
  { text: "acknowledge an alert", category: C4 },
  { text: "page the on-call", category: C4 },
  { text: "escalate an incident", category: C4 },
  { text: "declare an incident", category: C4 },
  { text: "stand down", category: C4 },
  { text: "the error rate spikes", category: C4 },
  { text: "latency degrades", category: C4 },
  { text: "a service is degraded", category: C4 },
  { text: "a partial outage", category: C4 },
  { text: "identify the root cause", category: C4 },
  { text: "mitigate the impact", category: C4 },
  { text: "restore service", category: C4 },
  { text: "return to baseline", category: C4 },
  { text: "write a postmortem", category: C4 },
  { text: "assign an action item", category: C4 },
  { text: "exhaust a connection pool", category: C4 },
  { text: "saturate a queue", category: C4 },
  { text: "a cascading failure", category: C4 },
  { text: "a thundering herd", category: C4 },

  // C.5 · Arquitectura y datos
  { text: "draw a boundary", category: C5 },
  { text: "decouple two services", category: C5 },
  { text: "introduce a dependency", category: C5 },
  { text: "invert a dependency", category: C5 },
  { text: "enforce a contract", category: C5 },
  { text: "version an API", category: C5 },
  { text: "deprecate an endpoint", category: C5 },
  { text: "expose an endpoint", category: C5 },
  { text: "consume an event", category: C5 },
  { text: "emit an event", category: C5 },
  { text: "shard a table", category: C5 },
  { text: "partition by date", category: C5 },
  { text: "index a column", category: C5 },
  { text: "run a query", category: C5 },
  { text: "the query plan", category: C5 },
  { text: "a full table scan", category: C5 },
  { text: "a cache hit / miss", category: C5 },
  { text: "invalidate a cache", category: C5 },
  { text: "warm the cache", category: C5 },
  { text: "evict an entry", category: C5 },
  { text: "eventual consistency", category: C5 },
  { text: "a read replica", category: C5 },
  { text: "a write-ahead log", category: C5 },
  { text: "a dead-letter queue", category: C5 },
  { text: "backfill data", category: C5 },
  { text: "replay events", category: C5 },

  // C.6 · Trabajo y proceso
  { text: "give an estimate", category: C6 },
  { text: "pad an estimate", category: C6 },
  { text: "meet a deadline", category: C6 },
  { text: "miss a deadline", category: C6 },
  { text: "push back a deadline", category: C6 },
  { text: "cut scope", category: C6 },
  { text: "raise a concern", category: C6 },
  { text: "flag a risk", category: C6 },
  { text: "unblock someone", category: C6 },
  { text: "be blocked on X", category: C6 },
  { text: "take ownership of X", category: C6 },
  { text: "hand over ownership", category: C6 },
  { text: "make a call", category: C6 },
  { text: "defer a decision", category: C6 },
  { text: "reach a consensus", category: C6 },
  { text: "agree to disagree", category: C6 },
  { text: "set expectations", category: C6 },
  { text: "manage up", category: C6 },
  { text: "run a meeting", category: C6 },
  { text: "chair a meeting", category: C6 },
  { text: "take minutes", category: C6 },
  { text: "circulate notes", category: C6 },
  { text: "pair on something", category: C6 },
  { text: "do a spike", category: C6 },
  { text: "groom the backlog", category: C6 },
  { text: "size a ticket", category: C6 },
  { text: "break down a task", category: C6 },
  { text: "timebox an activity", category: C6 },
  { text: "draw a line under it", category: C6 },
  { text: "park a topic", category: C6 },

  // C.7 · Verbos de alta frecuencia y su objeto natural
  {
    text: "make + a decision, a change, a mistake, progress, a call, sense, a suggestion, an assumption",
    category: C7,
    noteEs: "make a decision (no take, en US) · make sense (no have sense) · make progress (no do progress)",
  },
  {
    text: "take + a look, ownership, a decision [UK], responsibility, precedence, priority, a break",
    category: C7,
    noteEs: "take a look (no give a look)",
  },
  {
    text: "do + a review, research, testing, a spike, the work",
    category: C7,
    noteEs: "do research (no make research)",
  },
  {
    text: "give + feedback, an estimate, a heads-up, a demo, access",
    category: C7,
    noteEs: "give feedback (no make feedback)",
  },
  { text: "raise + a concern, an issue, a PR, an exception, a ticket", category: C7 },
  { text: "run + a test, a query, a service, a migration, an experiment", category: C7 },
  { text: "hit + a limit, a wall, a deadline, an edge case", category: C7 },
  { text: "meet + a requirement, a deadline, a threshold, expectations", category: C7 },
  { text: "address + a comment, a concern, an issue, the root cause", category: C7 },
  { text: "draw + a boundary, a conclusion, a distinction, a diagram", category: C7 },
];
