/**
 * Apéndice D — Falsos amigos (60).
 * Transcripción fiel del libro fuente: qué NO significa, qué significa
 * y qué usar en inglés para decir lo que se creía.
 */
import type { FalseFriend } from "@/domain/reference/reference";

export const FALSE_FRIENDS: FalseFriend[] = [
  { english: "actual(ly)", notMeaningEs: "actual(mente)", meaningEs: "real(mente), de hecho", useInsteadEn: "current(ly)" },
  { english: "eventual(ly)", notMeaningEs: "eventual(mente)", meaningEs: "finalmente, al final", useInsteadEn: "possibly, occasionally" },
  { english: "realize", notMeaningEs: "realizar", meaningEs: "darse cuenta", useInsteadEn: "carry out, perform, do" },
  { english: "assist", notMeaningEs: "asistir (a)", meaningEs: "ayudar", useInsteadEn: "attend" },
  { english: "support", notMeaningEs: "soportar (aguantar)", meaningEs: "apoyar, dar soporte", useInsteadEn: "withstand, tolerate, put up with" },
  { english: "library", notMeaningEs: "librería (tienda)", meaningEs: "biblioteca; librería de código", useInsteadEn: "bookshop / bookstore" },
  { english: "sensible", notMeaningEs: "sensible", meaningEs: "sensato, razonable", useInsteadEn: "sensitive" },
  { english: "sensitive", notMeaningEs: "sensato", meaningEs: "sensible; confidencial", useInsteadEn: "sensible" },
  { english: "deprecate", notMeaningEs: "depreciar (valor)", meaningEs: "marcar como obsoleto", useInsteadEn: "depreciate" },
  { english: "advertise", notMeaningEs: "advertir", meaningEs: "anunciar, publicitar", useInsteadEn: "warn" },
  { english: "argument", notMeaningEs: "argumento (de una obra)", meaningEs: "discusión; argumento de función", useInsteadEn: "plot; reasoning" },
  { english: "assume", notMeaningEs: "asumir (responsabilidad)", meaningEs: "suponer", useInsteadEn: "take on" },
  { english: "attend", notMeaningEs: "atender (a alguien)", meaningEs: "asistir a", useInsteadEn: "serve, deal with" },
  { english: "billion", notMeaningEs: "billón (10¹²)", meaningEs: "mil millones (10⁹)", useInsteadEn: "trillion" },
  { english: "carpet", notMeaningEs: "carpeta", meaningEs: "alfombra", useInsteadEn: "folder" },
  { english: "casual(ty)", notMeaningEs: "casual(idad)", meaningEs: "informal / víctima", useInsteadEn: "coincidence" },
  { english: "collar", notMeaningEs: "collar", meaningEs: "cuello (de camisa)", useInsteadEn: "necklace" },
  { english: "command", notMeaningEs: "comanda", meaningEs: "orden, comando", useInsteadEn: "order" },
  { english: "commodity", notMeaningEs: "comodidad", meaningEs: "materia prima, bien genérico", useInsteadEn: "comfort, convenience" },
  { english: "compromise", notMeaningEs: "compromiso", meaningEs: "acuerdo con concesiones", useInsteadEn: "commitment" },
  { english: "conductor", notMeaningEs: "conductor", meaningEs: "director de orquesta / revisor", useInsteadEn: "driver" },
  { english: "constipated", notMeaningEs: "constipado", meaningEs: "estreñido", useInsteadEn: "to have a cold" },
  { english: "contest", notMeaningEs: "contestar", meaningEs: "concurso; impugnar", useInsteadEn: "answer, reply" },
  { english: "convenient", notMeaningEs: "conveniente (recomendable)", meaningEs: "cómodo, práctico", useInsteadEn: "advisable" },
  { english: "deception", notMeaningEs: "decepción", meaningEs: "engaño", useInsteadEn: "disappointment" },
  { english: "definitely", notMeaningEs: "definitivamente (final)", meaningEs: "sin duda, seguro", useInsteadEn: "permanently, for good" },
  { english: "discuss", notMeaningEs: "discutir (pelear)", meaningEs: "tratar, hablar de", useInsteadEn: "argue" },
  { english: "doubt", notMeaningEs: "duda (pregunta)", meaningEs: "duda (incertidumbre)", useInsteadEn: "question" },
  { english: "embarrassed", notMeaningEs: "embarazada", meaningEs: "avergonzado", useInsteadEn: "pregnant" },
  { english: "estimate", notMeaningEs: "estimar (apreciar)", meaningEs: "estimar (calcular)", useInsteadEn: "value, appreciate" },
  { english: "exit", notMeaningEs: "éxito", meaningEs: "salida", useInsteadEn: "success" },
  { english: "fabric", notMeaningEs: "fábrica", meaningEs: "tejido", useInsteadEn: "factory" },
  { english: "facility", notMeaningEs: "facilidad", meaningEs: "instalación", useInsteadEn: "ease" },
  { english: "grave", notMeaningEs: "grave (enfermedad)", meaningEs: "tumba; serio", useInsteadEn: "serious, severe" },
  { english: "idiom", notMeaningEs: "idioma", meaningEs: "expresión idiomática", useInsteadEn: "language" },
  { english: "ignore", notMeaningEs: "ignorar (no saber)", meaningEs: "hacer caso omiso", useInsteadEn: "not know, be unaware" },
  { english: "inconvenient", notMeaningEs: "inconveniente (objeción)", meaningEs: "incómodo, inoportuno", useInsteadEn: "drawback, downside" },
  { english: "intoxicated", notMeaningEs: "intoxicado", meaningEs: "ebrio", useInsteadEn: "poisoned" },
  { english: "large", notMeaningEs: "largo", meaningEs: "grande", useInsteadEn: "long" },
  { english: "lecture", notMeaningEs: "lectura", meaningEs: "conferencia, clase", useInsteadEn: "reading" },
  { english: "notice", notMeaningEs: "noticia", meaningEs: "aviso; darse cuenta", useInsteadEn: "news" },
  { english: "parents", notMeaningEs: "parientes", meaningEs: "padres", useInsteadEn: "relatives" },
  { english: "particular", notMeaningEs: "particular (privado)", meaningEs: "específico, concreto", useInsteadEn: "private" },
  { english: "pretend", notMeaningEs: "pretender", meaningEs: "fingir", useInsteadEn: "intend, aim to" },
  { english: "preservative", notMeaningEs: "preservativo", meaningEs: "conservante", useInsteadEn: "condom" },
  { english: "process", notMeaningEs: "proceso (judicial)", meaningEs: "proceso; procesar", useInsteadEn: "trial, lawsuit" },
  { english: "question", notMeaningEs: "cuestión (asunto)", meaningEs: "pregunta", useInsteadEn: "matter, issue" },
  { english: "quiet", notMeaningEs: "quieto", meaningEs: "silencioso", useInsteadEn: "still" },
  { english: "quote", notMeaningEs: "cuota", meaningEs: "cita; presupuesto", useInsteadEn: "quota, fee" },
  { english: "record", notMeaningEs: "recordar", meaningEs: "registrar, grabar", useInsteadEn: "remember, remind" },
  { english: "regular", notMeaningEs: "regular (mediocre)", meaningEs: "habitual, normal", useInsteadEn: "average, so-so" },
  { english: "remove", notMeaningEs: "remover (agitar)", meaningEs: "quitar, eliminar", useInsteadEn: "stir" },
  { english: "resume", notMeaningEs: "resumir", meaningEs: "reanudar", useInsteadEn: "summarise" },
  { english: "retire", notMeaningEs: "retirar", meaningEs: "jubilarse", useInsteadEn: "withdraw, remove" },
  { english: "rope", notMeaningEs: "ropa", meaningEs: "cuerda", useInsteadEn: "clothes" },
  { english: "scale", notMeaningEs: "escalar (montaña)", meaningEs: "escala; escalar (sistemas)", useInsteadEn: "climb" },
  { english: "soap", notMeaningEs: "sopa", meaningEs: "jabón", useInsteadEn: "soup" },
  { english: "subject", notMeaningEs: "sujeto (persona)", meaningEs: "tema; asignatura; sujeto gram.", useInsteadEn: "individual, person" },
  { english: "success", notMeaningEs: "suceso", meaningEs: "éxito", useInsteadEn: "event, incident" },
  { english: "sympathetic", notMeaningEs: "simpático", meaningEs: "comprensivo", useInsteadEn: "nice, friendly" },
  { english: "target", notMeaningEs: "tarjeta", meaningEs: "objetivo", useInsteadEn: "card" },
  { english: "topic", notMeaningEs: "tópico (cliché)", meaningEs: "tema", useInsteadEn: "cliché" },
  { english: "ultimately", notMeaningEs: "últimamente", meaningEs: "en última instancia", useInsteadEn: "lately, recently" },
];
