/**
 * Apéndice F — Glosario técnico ES→EN con pronunciación.
 * Transcripción fiel del libro fuente (documento del proyecto).
 */
import type { GlossaryEntry } from "@/domain/reference/reference";

export const GLOSSARY: GlossaryEntry[] = [
  { es: "almacenamiento", en: "storage", ipa: "/ˈstɔːrɪdʒ/" },
  { es: "ámbito, alcance", en: "scope", ipa: "/skoʊp/" },
  { es: "arquitectura", en: "architecture", ipa: "/ˈɑːrkɪtektʃər/", noteEs: "acento en la 1ª" },
  { es: "asíncrono", en: "asynchronous / async", ipa: "/eɪˈsɪŋkrənəs/ /ˈeɪsɪŋk/", noteEs: "\"EI-sink\"" },
  { es: "bajar de versión", en: "downgrade", ipa: "/ˈdaʊngreɪd/" },
  { es: "base de datos", en: "database", ipa: "/ˈdeɪtəbeɪs/" },
  { es: "biblioteca", en: "library", ipa: "/ˈlaɪbreri/", noteEs: "\"LAI-bre-ri\"" },
  { es: "bucle", en: "loop", ipa: "/luːp/" },
  { es: "caché", en: "cache", ipa: "/kæʃ/", noteEs: "= cash" },
  { es: "cadena", en: "string", ipa: "/strɪŋ/" },
  { es: "carga", en: "load", ipa: "/loʊd/" },
  { es: "cifrado", en: "encryption", ipa: "/ɪnˈkrɪpʃən/" },
  { es: "clave ajena", en: "foreign key", ipa: "/ˈfɔːrən kiː/", noteEs: "g muda" },
  { es: "cola", en: "queue", ipa: "/kjuː/", noteEs: "\"kiu\"" },
  { es: "commit, confirmación", en: "commit", ipa: "/kəˈmɪt/", noteEs: "acento en la 2ª" },
  { es: "compilar", en: "compile", ipa: "/kəmˈpaɪl/" },
  { es: "consulta", en: "query", ipa: "/ˈkwɪri/" },
  { es: "contenedor", en: "container", ipa: "/kənˈteɪnər/" },
  { es: "copia de seguridad", en: "backup", ipa: "/ˈbækʌp/" },
  { es: "correo basura", en: "spam", ipa: "/spæm/" },
  { es: "cortafuegos", en: "firewall", ipa: "/ˈfaɪərwɔːl/" },
  { es: "depuración", en: "debugging", ipa: "/diːˈbʌgɪŋ/" },
  { es: "desarrollo", en: "development", ipa: "/dɪˈveləpmənt/", noteEs: "acento en vel" },
  { es: "desplegar", en: "deploy", ipa: "/dɪˈplɔɪ/" },
  { es: "despliegue gradual", en: "gradual rollout", ipa: "/ˈgrædʒuəl/" },
  { es: "deuda técnica", en: "technical debt", ipa: "/det/", noteEs: "b muda" },
  { es: "diseño", en: "design", ipa: "/dɪˈzaɪn/" },
  { es: "entorno", en: "environment", ipa: "/ɪnˈvaɪrənmənt/" },
  { es: "entrega continua", en: "continuous delivery", ipa: "/kənˈtɪnjuəs/" },
  { es: "enrutamiento", en: "routing", ipa: "/ˈruːtɪŋ/ [UK] /ˈraʊtɪŋ/ [US]" },
  { es: "error tipográfico", en: "typo", ipa: "/ˈtaɪpoʊ/" },
  { es: "esquema", en: "schema", ipa: "/ˈskiːmə/", noteEs: "\"SKII-ma\"" },
  { es: "etiqueta", en: "tag / label", ipa: "/tæg/ /ˈleɪbəl/" },
  { es: "fallo", en: "failure", ipa: "/ˈfeɪljər/" },
  { es: "fiabilidad", en: "reliability", ipa: "/rɪˌlaɪəˈbɪləti/" },
  { es: "flujo", en: "flow / stream", ipa: "/floʊ/ /striːm/" },
  { es: "fuga de memoria", en: "memory leak", ipa: "/liːk/", noteEs: "⚠️ no /lɪk/" },
  { es: "función", en: "function", ipa: "/ˈfʌŋkʃən/" },
  { es: "hilo", en: "thread", ipa: "/θred/", noteEs: "/θ/ + /r/" },
  { es: "implementar", en: "implement", ipa: "/ˈɪmplɪment/", noteEs: "⚠️ no \"to implement a feature\" = desplegar" },
  { es: "índice", en: "index (pl. indexes/indices)", ipa: "/ˈɪndeks/" },
  { es: "interfaz", en: "interface", ipa: "/ˈɪntərfeɪs/" },
  { es: "iterar", en: "iterate", ipa: "/ˈɪtəreɪt/" },
  { es: "latencia", en: "latency", ipa: "/ˈleɪtənsi/", noteEs: "\"LEI-ten-si\"" },
  { es: "lenguaje", en: "language", ipa: "/ˈlæŋgwɪdʒ/" },
  { es: "marco de trabajo", en: "framework", ipa: "/ˈfreɪmwɜːrk/" },
  { es: "memoria", en: "memory", ipa: "/ˈmeməri/" },
  { es: "mensaje", en: "message", ipa: "/ˈmesɪdʒ/" },
  { es: "nivel de servicio", en: "SLA", ipa: "/es el ˈeɪ/", noteEs: "letra a letra" },
  { es: "nube", en: "cloud", ipa: "/klaʊd/" },
  { es: "nulo", en: "null", ipa: "/nʌl/", noteEs: "⚠️ no \"nul\"" },
  { es: "paralelismo", en: "concurrency", ipa: "/kənˈkɜːrənsi/" },
  { es: "partición", en: "partition", ipa: "/pɑːrˈtɪʃən/" },
  { es: "permiso", en: "permission", ipa: "/pərˈmɪʃən/" },
  { es: "peticiones por segundo", en: "requests per second (rps)", ipa: "/rɪˈkwests/" },
  { es: "plazo", en: "deadline", ipa: "/ˈdedlaɪn/" },
  { es: "prueba", en: "test", ipa: "/test/" },
  { es: "prueba de concepto", en: "proof of concept (PoC)", ipa: "/pruːf/" },
  { es: "puerto", en: "port", ipa: "/pɔːrt/" },
  { es: "punto final", en: "endpoint", ipa: "/ˈendpɔɪnt/" },
  { es: "rama", en: "branch", ipa: "/bræntʃ/" },
  { es: "red", en: "network", ipa: "/ˈnetwɜːrk/" },
  { es: "registro", en: "log", ipa: "/lɔːg/" },
  { es: "rendimiento", en: "performance", ipa: "/pərˈfɔːrməns/" },
  { es: "requisito", en: "requirement", ipa: "/rɪˈkwaɪərmənt/" },
  { es: "respaldo", en: "fallback", ipa: "/ˈfɔːlbæk/" },
  { es: "retroceso exponencial", en: "exponential backoff", ipa: "/ˌekspəˈnenʃəl/" },
  { es: "reversión", en: "rollback", ipa: "/ˈroʊlbæk/" },
  { es: "revisión de código", en: "code review", ipa: "/rɪˈvjuː/" },
  { es: "seguridad", en: "security", ipa: "/sɪˈkjʊrəti/" },
  { es: "servidor", en: "server", ipa: "/ˈsɜːrvər/" },
  { es: "sobrecarga", en: "overhead", ipa: "/ˈoʊvərhed/" },
  { es: "sondeo", en: "polling", ipa: "/ˈpoʊlɪŋ/" },
  { es: "tabla", en: "table", ipa: "/ˈteɪbəl/" },
  { es: "tiempo de espera", en: "timeout", ipa: "/ˈtaɪmaʊt/" },
  { es: "tiempo de inactividad", en: "downtime", ipa: "/ˈdaʊntaɪm/" },
  { es: "tipo de dato", en: "data type", ipa: "/ˈdeɪtə/ [US] /ˈdɑːtə/ [UK]" },
  { es: "tubería, canalización", en: "pipeline", ipa: "/ˈpaɪplaɪn/" },
  { es: "tupla", en: "tuple", ipa: "/ˈtʌpəl/ o /ˈtuːpəl/" },
  { es: "umbral", en: "threshold", ipa: "/ˈθreʃhoʊld/", noteEs: "/θ/ inicial" },
  { es: "valor por defecto", en: "default", ipa: "/dɪˈfɔːlt/", noteEs: "acento en la 2ª" },
  { es: "variable", en: "variable", ipa: "/ˈveriəbəl/", noteEs: "acento en la 1ª" },
  { es: "versión", en: "release", ipa: "/rɪˈliːs/" },
  { es: "vulnerabilidad", en: "vulnerability", ipa: "/ˌvʌlnərəˈbɪləti/" },
];
