/**
 * Apéndice A — Verbos irregulares (100, con pronunciación).
 * Transcripción fiel del libro fuente, agrupados por patrón (A.1–A.4).
 * En el patrón "double-form" la primera variante es US y la segunda UK.
 */
import type { IrregularVerb } from "@/domain/reference/reference";

export const IRREGULAR_VERBS: IrregularVerb[] = [
  // A.1 · Las tres formas iguales
  { base: "bet", past: "bet", participle: "bet", ipa: "/bet/", glossEs: "apostar", pattern: "all-same" },
  { base: "burst", past: "burst", participle: "burst", ipa: "/bɜːrst/", glossEs: "estallar", pattern: "all-same" },
  { base: "cast", past: "cast", participle: "cast", ipa: "/kæst/", glossEs: "lanzar; convertir tipo", pattern: "all-same" },
  { base: "cost", past: "cost", participle: "cost", ipa: "/kɔːst/", glossEs: "costar", pattern: "all-same" },
  { base: "cut", past: "cut", participle: "cut", ipa: "/kʌt/", glossEs: "cortar", pattern: "all-same" },
  { base: "hit", past: "hit", participle: "hit", ipa: "/hɪt/", glossEs: "golpear; alcanzar (un límite)", pattern: "all-same" },
  { base: "hurt", past: "hurt", participle: "hurt", ipa: "/hɜːrt/", glossEs: "doler", pattern: "all-same" },
  { base: "let", past: "let", participle: "let", ipa: "/let/", glossEs: "permitir", pattern: "all-same" },
  { base: "put", past: "put", participle: "put", ipa: "/pʊt/", glossEs: "poner", pattern: "all-same" },
  { base: "quit", past: "quit", participle: "quit", ipa: "/kwɪt/", glossEs: "abandonar; salir", pattern: "all-same" },
  { base: "read", past: "read", participle: "read", ipa: "/riːd/ · /red/ · /red/", glossEs: "leer ⚠️ misma grafía, distinto sonido", pattern: "all-same" },
  { base: "reset", past: "reset", participle: "reset", ipa: "/riːˈset/", glossEs: "reiniciar", pattern: "all-same" },
  { base: "set", past: "set", participle: "set", ipa: "/set/", glossEs: "establecer", pattern: "all-same" },
  { base: "shut", past: "shut", participle: "shut", ipa: "/ʃʌt/", glossEs: "cerrar", pattern: "all-same" },
  { base: "split", past: "split", participle: "split", ipa: "/splɪt/", glossEs: "dividir", pattern: "all-same" },
  { base: "spread", past: "spread", participle: "spread", ipa: "/spred/ · /spred/", glossEs: "extender", pattern: "all-same" },

  // A.2 · Pasado y participio iguales
  { base: "bring", past: "brought", participle: "brought", ipa: "/brɔːt/", glossEs: "traer", pattern: "past-eq-participle" },
  { base: "build", past: "built", participle: "built", ipa: "/bɪlt/", glossEs: "construir", pattern: "past-eq-participle" },
  { base: "buy", past: "bought", participle: "bought", ipa: "/bɔːt/", glossEs: "comprar", pattern: "past-eq-participle" },
  { base: "catch", past: "caught", participle: "caught", ipa: "/kɔːt/", glossEs: "atrapar; capturar (excepción)", pattern: "past-eq-participle" },
  { base: "deal", past: "dealt", participle: "dealt", ipa: "/delt/", glossEs: "tratar (with)", pattern: "past-eq-participle" },
  { base: "feed", past: "fed", participle: "fed", ipa: "/fed/", glossEs: "alimentar", pattern: "past-eq-participle" },
  { base: "feel", past: "felt", participle: "felt", ipa: "/felt/", glossEs: "sentir", pattern: "past-eq-participle" },
  { base: "fight", past: "fought", participle: "fought", ipa: "/fɔːt/", glossEs: "luchar", pattern: "past-eq-participle" },
  { base: "find", past: "found", participle: "found", ipa: "/faʊnd/", glossEs: "encontrar", pattern: "past-eq-participle" },
  { base: "get", past: "got", participle: "got", ipa: "/gɑːt/", glossEs: "obtener", pattern: "past-eq-participle" },
  { base: "hang", past: "hung", participle: "hung", ipa: "/hʌŋ/", glossEs: "colgar; quedarse colgado", pattern: "past-eq-participle" },
  { base: "have", past: "had", participle: "had", ipa: "/hæd/", glossEs: "tener", pattern: "past-eq-participle" },
  { base: "hear", past: "heard", participle: "heard", ipa: "/hɜːrd/", glossEs: "oír", pattern: "past-eq-participle" },
  { base: "hold", past: "held", participle: "held", ipa: "/held/", glossEs: "sostener; mantener (un lock)", pattern: "past-eq-participle" },
  { base: "keep", past: "kept", participle: "kept", ipa: "/kept/", glossEs: "mantener", pattern: "past-eq-participle" },
  { base: "lead", past: "led", participle: "led", ipa: "/led/", glossEs: "liderar", pattern: "past-eq-participle" },
  { base: "leave", past: "left", participle: "left", ipa: "/left/", glossEs: "dejar; salir", pattern: "past-eq-participle" },
  { base: "lend", past: "lent", participle: "lent", ipa: "/lent/", glossEs: "prestar", pattern: "past-eq-participle" },
  { base: "lose", past: "lost", participle: "lost", ipa: "/lɔːst/", glossEs: "perder", pattern: "past-eq-participle" },
  { base: "make", past: "made", participle: "made", ipa: "/meɪd/", glossEs: "hacer", pattern: "past-eq-participle" },
  { base: "mean", past: "meant", participle: "meant", ipa: "/ment/", glossEs: "significar ⚠️ /e/, no /iː/", pattern: "past-eq-participle" },
  { base: "meet", past: "met", participle: "met", ipa: "/met/", glossEs: "conocer; cumplir (un requisito)", pattern: "past-eq-participle" },
  { base: "pay", past: "paid", participle: "paid", ipa: "/peɪd/", glossEs: "pagar", pattern: "past-eq-participle" },
  { base: "say", past: "said", participle: "said", ipa: "/sed/", glossEs: "decir ⚠️ /e/", pattern: "past-eq-participle" },
  { base: "sell", past: "sold", participle: "sold", ipa: "/soʊld/", glossEs: "vender", pattern: "past-eq-participle" },
  { base: "send", past: "sent", participle: "sent", ipa: "/sent/", glossEs: "enviar", pattern: "past-eq-participle" },
  { base: "shoot", past: "shot", participle: "shot", ipa: "/ʃɑːt/", glossEs: "disparar", pattern: "past-eq-participle" },
  { base: "sit", past: "sat", participle: "sat", ipa: "/sæt/", glossEs: "sentarse", pattern: "past-eq-participle" },
  { base: "sleep", past: "slept", participle: "slept", ipa: "/slept/", glossEs: "dormir", pattern: "past-eq-participle" },
  { base: "spend", past: "spent", participle: "spent", ipa: "/spent/", glossEs: "gastar", pattern: "past-eq-participle" },
  { base: "stand", past: "stood", participle: "stood", ipa: "/stʊd/", glossEs: "estar de pie; soportar", pattern: "past-eq-participle" },
  { base: "teach", past: "taught", participle: "taught", ipa: "/tɔːt/", glossEs: "enseñar", pattern: "past-eq-participle" },
  { base: "tell", past: "told", participle: "told", ipa: "/toʊld/", glossEs: "decir a alguien", pattern: "past-eq-participle" },
  { base: "think", past: "thought", participle: "thought", ipa: "/θɔːt/", glossEs: "pensar", pattern: "past-eq-participle" },
  { base: "understand", past: "understood", participle: "understood", ipa: "/ˌʌndərˈstʊd/", glossEs: "entender", pattern: "past-eq-participle" },
  { base: "win", past: "won", participle: "won", ipa: "/wʌn/", glossEs: "ganar ⚠️ = one", pattern: "past-eq-participle" },

  // A.3 · Las tres formas distintas
  { base: "be", past: "was/were", participle: "been", ipa: "/wɒz, wɜːr/ /bɪn/", glossEs: "ser/estar", pattern: "all-different" },
  { base: "begin", past: "began", participle: "begun", ipa: "/bɪˈgæn/ /bɪˈgʌn/", glossEs: "empezar", pattern: "all-different" },
  { base: "break", past: "broke", participle: "broken", ipa: "/broʊk/ /ˈbroʊkən/", glossEs: "romper", pattern: "all-different" },
  { base: "choose", past: "chose", participle: "chosen", ipa: "/tʃoʊz/ /ˈtʃoʊzən/", glossEs: "elegir", pattern: "all-different" },
  { base: "come", past: "came", participle: "come", ipa: "/keɪm/ /kʌm/", glossEs: "venir", pattern: "all-different" },
  { base: "do", past: "did", participle: "done", ipa: "/dɪd/ /dʌn/", glossEs: "hacer", pattern: "all-different" },
  { base: "draw", past: "drew", participle: "drawn", ipa: "/druː/ /drɔːn/", glossEs: "dibujar", pattern: "all-different" },
  { base: "drink", past: "drank", participle: "drunk", ipa: "/dræŋk/ /drʌŋk/", glossEs: "beber", pattern: "all-different" },
  { base: "drive", past: "drove", participle: "driven", ipa: "/droʊv/ /ˈdrɪvən/", glossEs: "conducir; impulsar", pattern: "all-different" },
  { base: "eat", past: "ate", participle: "eaten", ipa: "/eɪt/ /ˈiːtən/", glossEs: "comer", pattern: "all-different" },
  { base: "fall", past: "fell", participle: "fallen", ipa: "/fel/ /ˈfɔːlən/", glossEs: "caer", pattern: "all-different" },
  { base: "fly", past: "flew", participle: "flown", ipa: "/fluː/ /floʊn/", glossEs: "volar", pattern: "all-different" },
  { base: "forget", past: "forgot", participle: "forgotten", ipa: "/fərˈgɑːt/ /fərˈgɑːtən/", glossEs: "olvidar", pattern: "all-different" },
  { base: "freeze", past: "froze", participle: "frozen", ipa: "/froʊz/ /ˈfroʊzən/", glossEs: "congelar", pattern: "all-different" },
  { base: "give", past: "gave", participle: "given", ipa: "/geɪv/ /ˈgɪvən/", glossEs: "dar", pattern: "all-different" },
  { base: "go", past: "went", participle: "gone", ipa: "/went/ /gɔːn/", glossEs: "ir", pattern: "all-different" },
  { base: "grow", past: "grew", participle: "grown", ipa: "/gruː/ /groʊn/", glossEs: "crecer", pattern: "all-different" },
  { base: "know", past: "knew", participle: "known", ipa: "/nuː/ /noʊn/", glossEs: "saber ⚠️ k muda", pattern: "all-different" },
  { base: "ring", past: "rang", participle: "rung", ipa: "/ræŋ/ /rʌŋ/", glossEs: "sonar", pattern: "all-different" },
  { base: "rise", past: "rose", participle: "risen", ipa: "/roʊz/ /ˈrɪzən/", glossEs: "subir (intransitivo)", pattern: "all-different" },
  { base: "run", past: "ran", participle: "run", ipa: "/ræn/ /rʌn/", glossEs: "correr; ejecutar", pattern: "all-different" },
  { base: "see", past: "saw", participle: "seen", ipa: "/sɔː/ /siːn/", glossEs: "ver", pattern: "all-different" },
  { base: "shake", past: "shook", participle: "shaken", ipa: "/ʃʊk/ /ˈʃeɪkən/", glossEs: "agitar", pattern: "all-different" },
  { base: "show", past: "showed", participle: "shown", ipa: "/ʃoʊd/ /ʃoʊn/", glossEs: "mostrar", pattern: "all-different" },
  { base: "shrink", past: "shrank", participle: "shrunk", ipa: "/ʃræŋk/ /ʃrʌŋk/", glossEs: "encoger", pattern: "all-different" },
  { base: "sing", past: "sang", participle: "sung", ipa: "/sæŋ/ /sʌŋ/", glossEs: "cantar", pattern: "all-different" },
  { base: "sink", past: "sank", participle: "sunk", ipa: "/sæŋk/ /sʌŋk/", glossEs: "hundirse", pattern: "all-different" },
  { base: "speak", past: "spoke", participle: "spoken", ipa: "/spoʊk/ /ˈspoʊkən/", glossEs: "hablar", pattern: "all-different" },
  { base: "steal", past: "stole", participle: "stolen", ipa: "/stoʊl/ /ˈstoʊlən/", glossEs: "robar", pattern: "all-different" },
  { base: "swim", past: "swam", participle: "swum", ipa: "/swæm/ /swʌm/", glossEs: "nadar", pattern: "all-different" },
  { base: "take", past: "took", participle: "taken", ipa: "/tʊk/ /ˈteɪkən/", glossEs: "tomar", pattern: "all-different" },
  { base: "tear", past: "tore", participle: "torn", ipa: "/tɔːr/ /tɔːrn/", glossEs: "desgarrar", pattern: "all-different" },
  { base: "throw", past: "threw", participle: "thrown", ipa: "/θruː/ /θroʊn/", glossEs: "lanzar; lanzar (excepción)", pattern: "all-different" },
  { base: "wake", past: "woke", participle: "woken", ipa: "/woʊk/ /ˈwoʊkən/", glossEs: "despertar", pattern: "all-different" },
  { base: "wear", past: "wore", participle: "worn", ipa: "/wɔːr/ /wɔːrn/", glossEs: "llevar puesto", pattern: "all-different" },
  { base: "write", past: "wrote", participle: "written", ipa: "/roʊt/ /ˈrɪtən/", glossEs: "escribir ⚠️ w muda", pattern: "all-different" },

  // A.4 · Con doble forma (US / UK)
  { base: "burn", past: "burned / burnt", participle: "burned / burnt", glossEs: "quemar", pattern: "double-form" },
  { base: "dream", past: "dreamed / dreamt", participle: "dreamed / dreamt", glossEs: "soñar", pattern: "double-form" },
  { base: "learn", past: "learned / learnt", participle: "learned / learnt", glossEs: "aprender", pattern: "double-form" },
  { base: "smell", past: "smelled / smelt", participle: "smelled / smelt", glossEs: "oler", pattern: "double-form" },
  { base: "spell", past: "spelled / spelt", participle: "spelled / spelt", glossEs: "deletrear", pattern: "double-form" },
  { base: "spill", past: "spilled / spilt", participle: "spilled / spilt", glossEs: "derramar", pattern: "double-form" },
  { base: "get (part.)", past: "got", participle: "gotten / got", glossEs: "obtenido", pattern: "double-form" },
  { base: "dive", past: "dove/dived / dived", participle: "dived", glossEs: "zambullirse", pattern: "double-form" },
  { base: "prove", past: "proved", participle: "proved/proven / proved", glossEs: "probar", pattern: "double-form" },
];
