/**
 * Apéndice B — Phrasal verbs para desarrolladores (120).
 * Transcripción fiel del libro fuente, agrupados por partícula (B.1–B.6)
 * en el mismo orden. `example` puede quedar vacío cuando el libro no lo da.
 */
import type { PhrasalVerb } from "@/domain/reference/reference";

export const PHRASAL_VERBS: PhrasalVerb[] = [
  // B.1 · up (completar, aumentar, crear)
  { verb: "set", particle: "up", meaningEs: "configurar", example: "Set up the dev environment." },
  { verb: "spin", particle: "up", meaningEs: "arrancar (una instancia)", example: "Spin up a new container." },
  { verb: "bring", particle: "up", meaningEs: "mencionar; arrancar", example: "Good point to bring up." },
  { verb: "back", particle: "up", meaningEs: "respaldar", example: "Back up the database first." },
  { verb: "clean", particle: "up", meaningEs: "limpiar", example: "Clean up the temp files." },
  { verb: "catch", particle: "up", meaningEs: "poner al día", example: "Let's catch up on Monday." },
  { verb: "end", particle: "up", meaningEs: "acabar (sin planearlo)", example: "We ended up rolling back." },
  { verb: "come", particle: "up", meaningEs: "surgir", example: "A blocker came up." },
  { verb: "come", particle: "up with", meaningEs: "idear", example: "He came up with a workaround." },
  { verb: "show", particle: "up", meaningEs: "aparecer", example: "It shows up in the logs." },
  { verb: "pick", particle: "up", meaningEs: "retomar; aprender", example: "I'll pick that up tomorrow." },
  { verb: "follow", particle: "up", meaningEs: "dar seguimiento", example: "I'll follow up by email." },
  { verb: "open", particle: "up", meaningEs: "abrir (posibilidades)", example: "That opens up new options." },
  { verb: "free", particle: "up", meaningEs: "liberar", example: "That frees up memory." },
  { verb: "use", particle: "up", meaningEs: "agotar", example: "We used up the quota." },
  { verb: "tie", particle: "up", meaningEs: "ocupar; bloquear", example: "The lock ties up the table." },
  { verb: "lock", particle: "up", meaningEs: "congelarse", example: "The UI locks up under load." },
  { verb: "hold", particle: "up", meaningEs: "resistir; retrasar", example: "Will it hold up at scale?" },
  { verb: "speed", particle: "up", meaningEs: "acelerar", example: "" },
  { verb: "scale", particle: "up", meaningEs: "escalar verticalmente", example: "" },
  { verb: "split", particle: "up", meaningEs: "dividir", example: "" },
  { verb: "break", particle: "up", meaningEs: "descomponer", example: "Break up the monolith." },
  { verb: "sum", particle: "up", meaningEs: "resumir", example: "" },
  { verb: "write", particle: "up", meaningEs: "redactar", example: "Write up the postmortem." },
  { verb: "draw", particle: "up", meaningEs: "elaborar", example: "Draw up a plan." },
  { verb: "fill", particle: "up", meaningEs: "llenarse", example: "The disk filled up." },
  { verb: "queue", particle: "up", meaningEs: "poner en cola", example: "" },
  { verb: "warm", particle: "up", meaningEs: "precalentar (caché)", example: "" },
  { verb: "own", particle: "up", meaningEs: "reconocer un error", example: "I owned up to it." },
  { verb: "escalate", particle: "up", meaningEs: "escalar (jerarquía)", example: "" },

  // B.2 · down (reducir, apagar, registrar)
  { verb: "shut", particle: "down", meaningEs: "apagar", example: "Shut down the service." },
  { verb: "break", particle: "down", meaningEs: "averiarse; desglosar", example: "Break down the estimate." },
  { verb: "go", particle: "down", meaningEs: "caerse (un servicio)", example: "The API went down." },
  { verb: "take", particle: "down", meaningEs: "tumbar", example: "It took down notifications." },
  { verb: "bring", particle: "down", meaningEs: "reducir; tumbar", example: "Bring down the latency." },
  { verb: "slow", particle: "down", meaningEs: "ralentizar", example: "" },
  { verb: "scale", particle: "down", meaningEs: "reducir escala", example: "" },
  { verb: "narrow", particle: "down", meaningEs: "acotar", example: "Narrow down the cause." },
  { verb: "track", particle: "down", meaningEs: "localizar", example: "Track down the leak." },
  { verb: "write", particle: "down", meaningEs: "apuntar", example: "" },
  { verb: "note", particle: "down", meaningEs: "anotar", example: "" },
  { verb: "lock", particle: "down", meaningEs: "bloquear (seguridad)", example: "" },
  { verb: "shut", particle: "down gracefully", meaningEs: "apagar de forma ordenada", example: "" },
  { verb: "water", particle: "down", meaningEs: "diluir (una propuesta)", example: "" },
  { verb: "step", particle: "down", meaningEs: "dimitir de un rol", example: "" },

  // B.3 · out (extraer, distribuir, resolver)
  { verb: "figure", particle: "out", meaningEs: "descubrir", example: "I figured out why." },
  { verb: "find", particle: "out", meaningEs: "averiguar", example: "" },
  { verb: "work", particle: "out", meaningEs: "resolver; funcionar", example: "It worked out fine." },
  { verb: "sort", particle: "out", meaningEs: "arreglar", example: "Sort out the config." },
  { verb: "iron", particle: "out", meaningEs: "pulir detalles", example: "" },
  { verb: "rule", particle: "out", meaningEs: "descartar", example: "We ruled out the network." },
  { verb: "point", particle: "out", meaningEs: "señalar", example: "She pointed out a bug." },
  { verb: "roll", particle: "out", meaningEs: "desplegar", example: "Roll out to 10% first." },
  { verb: "phase", particle: "out", meaningEs: "retirar gradualmente", example: "" },
  { verb: "pull", particle: "out", meaningEs: "retirar", example: "" },
  { verb: "filter", particle: "out", meaningEs: "filtrar (quitar)", example: "" },
  { verb: "time", particle: "out", meaningEs: "expirar", example: "The request timed out." },
  { verb: "run", particle: "out (of)", meaningEs: "agotarse", example: "We ran out of memory." },
  { verb: "burn", particle: "out", meaningEs: "quemarse", example: "" },
  { verb: "stand", particle: "out", meaningEs: "destacar", example: "" },
  { verb: "turn", particle: "out", meaningEs: "resultar", example: "It turned out to be a typo." },
  { verb: "reach", particle: "out", meaningEs: "contactar", example: "Reach out if you're stuck." },
  { verb: "sound", particle: "out", meaningEs: "tantear", example: "" },
  { verb: "flesh", particle: "out", meaningEs: "desarrollar (una idea)", example: "" },
  { verb: "carve", particle: "out", meaningEs: "reservar (tiempo)", example: "Carve out an hour." },
  { verb: "back", particle: "out", meaningEs: "echarse atrás; revertir", example: "Back out the change." },
  { verb: "bail", particle: "out", meaningEs: "abandonar; salir de emergencia", example: "" },
  { verb: "lay", particle: "out", meaningEs: "disponer; explicar", example: "Let me lay out the options." },
  { verb: "map", particle: "out", meaningEs: "mapear", example: "" },
  { verb: "spell", particle: "out", meaningEs: "explicar con detalle", example: "" },
  { verb: "play", particle: "out", meaningEs: "desarrollarse", example: "Let's see how it plays out." },
  { verb: "swap", particle: "out", meaningEs: "sustituir", example: "Swap out the driver." },
  { verb: "roll", particle: "back", meaningEs: "revertir", example: "Roll back to 4.11." },

  // B.4 · in / into
  { verb: "look", particle: "into", meaningEs: "investigar", example: "I'll look into it." },
  { verb: "dig", particle: "into", meaningEs: "profundizar", example: "" },
  { verb: "run", particle: "into", meaningEs: "encontrarse con (un problema)", example: "I ran into a race condition." },
  { verb: "plug", particle: "in", meaningEs: "conectar; integrar", example: "" },
  { verb: "check", particle: "in", meaningEs: "registrar; hacer seguimiento", example: "Let's check in Thursday." },
  { verb: "log", particle: "in", meaningEs: "iniciar sesión", example: "" },
  { verb: "bring", particle: "in", meaningEs: "incorporar", example: "Bring in the platform team." },
  { verb: "loop", particle: "in", meaningEs: "incluir en una conversación", example: "Looping in Maya." },
  { verb: "chip", particle: "in", meaningEs: "contribuir", example: "" },
  { verb: "factor", particle: "in", meaningEs: "tener en cuenta", example: "Factor in the review time." },
  { verb: "feed", particle: "into", meaningEs: "alimentar", example: "" },
  { verb: "tap", particle: "into", meaningEs: "aprovechar", example: "" },
  { verb: "fill", particle: "in", meaningEs: "rellenar; sustituir", example: "Fill in for me on Friday." },
  { verb: "take", particle: "in", meaningEs: "asimilar", example: "" },
  { verb: "break", particle: "into", meaningEs: "dividir en", example: "Break it into three PRs." },
  { verb: "buy", particle: "into", meaningEs: "aceptar (una idea)", example: "" },
  { verb: "get", particle: "into", meaningEs: "meterse en", example: "" },
  { verb: "jump", particle: "in", meaningEs: "intervenir", example: "Jump in if I've got it wrong." },

  // B.5 · on / off
  { verb: "carry", particle: "on", meaningEs: "continuar", example: "" },
  { verb: "move", particle: "on", meaningEs: "pasar a otra cosa", example: "" },
  { verb: "go", particle: "on", meaningEs: "ocurrir; continuar", example: "What's going on?" },
  { verb: "hold", particle: "on", meaningEs: "esperar", example: "" },
  { verb: "take", particle: "on", meaningEs: "asumir", example: "I'll take that on." },
  { verb: "work", particle: "on", meaningEs: "trabajar en", example: "" },
  { verb: "depend", particle: "on", meaningEs: "depender de ⚠️ nunca depend of", example: "" },
  { verb: "rely", particle: "on", meaningEs: "confiar en", example: "" },
  { verb: "focus", particle: "on", meaningEs: "centrarse en", example: "" },
  { verb: "catch", particle: "on", meaningEs: "cuajar; entender", example: "" },
  { verb: "sign", particle: "off (on)", meaningEs: "dar el visto bueno", example: "Can you sign off on this?" },
  { verb: "kick", particle: "off", meaningEs: "arrancar", example: "Kick off the migration." },
  { verb: "lay", particle: "off", meaningEs: "despedir", example: "" },
  { verb: "put", particle: "off", meaningEs: "posponer", example: "" },
  { verb: "call", particle: "off", meaningEs: "cancelar", example: "" },
  { verb: "back", particle: "off", meaningEs: "retroceder (retry)", example: "Back off exponentially." },
  { verb: "write", particle: "off", meaningEs: "dar por perdido", example: "" },
  { verb: "trade", particle: "off", meaningEs: "contraponer", example: "" },
  { verb: "pay", particle: "off", meaningEs: "dar resultado", example: "The refactor paid off." },
  { verb: "hand", particle: "off", meaningEs: "traspasar", example: "Hand off to the on-call." },
  { verb: "head", particle: "off", meaningEs: "prevenir", example: "" },
  { verb: "take", particle: "off", meaningEs: "despegar; crecer rápido", example: "" },
  { verb: "knock", particle: "off", meaningEs: "terminar (jornada)", example: "" },
  { verb: "cut", particle: "off", meaningEs: "cortar", example: "" },
  { verb: "fall", particle: "off", meaningEs: "disminuir", example: "" },

  // B.6 · over / through / around / apart
  { verb: "go", particle: "over", meaningEs: "revisar", example: "Let's go over the plan." },
  { verb: "look", particle: "over", meaningEs: "echar un vistazo", example: "" },
  { verb: "take", particle: "over", meaningEs: "tomar el control", example: "" },
  { verb: "hand", particle: "over", meaningEs: "entregar", example: "" },
  { verb: "roll", particle: "over", meaningEs: "transferir (al siguiente)", example: "" },
  { verb: "think", particle: "over", meaningEs: "reflexionar", example: "" },
  { verb: "talk", particle: "over", meaningEs: "hablar de; hablar por encima", example: "" },
  { verb: "get", particle: "over", meaningEs: "superar", example: "" },
  { verb: "walk", particle: "through", meaningEs: "explicar paso a paso", example: "Walk me through it." },
  { verb: "think", particle: "through", meaningEs: "pensar a fondo", example: "" },
  { verb: "go", particle: "through", meaningEs: "atravesar; repasar", example: "" },
  { verb: "follow", particle: "through", meaningEs: "llevar a término", example: "" },
  { verb: "push", particle: "through", meaningEs: "sacar adelante", example: "" },
  { verb: "fall", particle: "through", meaningEs: "fracasar", example: "The plan fell through." },
  { verb: "get", particle: "around", meaningEs: "eludir", example: "Get around the limit." },
  { verb: "get", particle: "around to", meaningEs: "llegar a hacer", example: "I never got around to it." },
  { verb: "work", particle: "around", meaningEs: "sortear", example: "" },
  { verb: "turn", particle: "around", meaningEs: "dar la vuelta; mejorar", example: "" },
  { verb: "come", particle: "around", meaningEs: "cambiar de opinión", example: "" },
  { verb: "take", particle: "apart", meaningEs: "desmontar", example: "" },
  { verb: "tell", particle: "apart", meaningEs: "distinguir", example: "" },
  { verb: "pull", particle: "apart", meaningEs: "desmenuzar", example: "" },
];
